package uk.co.wonderlane.wlpos.transactions

import org.apache.commons.lang3.StringUtils
import org.joda.time.DateTime
import uk.co.wonderlane.wlpos.entities.cash.TenderTotal
import com.google.gson.reflect.TypeToken
import java.lang.reflect.Type

class SafeSessionAudit {

    def gsonProvider

    int id
    int sessionId
    boolean autoGenerated
    String action
    int userId
    String userName
    String usersRealName
    DateTime timestamp
    String extrasJson
    Integer tenderMovementId
    String tenderMovementValueJson

    // This constructor is required or dependency injection
    public SafeSessionAudit() {}
    static mapping = {
        autowire true
        datasources(["transactions"])
        table "safesessionaudit"
        version false

        sessionId column: "sessionId"
        autoGenerated column: "autoGenerated"
        action column: "action"
        userId column: "userId"
        userName column: "userName"
        usersRealName column: "usersRealName"
        timestamp column: "timestamp"
        extrasJson column: "extras", type: "uk.co.wonderlane.wlpos.usertypes.JsonType", sqlType: "json"
        tenderMovementId column: "tenderMovementId"
        tenderMovementValueJson column: "tenderMovementValue", type: "uk.co.wonderlane.wlpos.usertypes.JsonType", sqlType: "json"
    }

    static constraints = { }

    public List<TenderTotal> getTenderMovementValues() {
        if (StringUtils.isNotBlank(tenderMovementValueJson)) {
            Type tenderTotalListType = new TypeToken<List<TenderTotal>>() {}.getType()
            return gsonProvider.gson.fromJson(tenderMovementValueJson, tenderTotalListType)
        }
        return null
    }

    public uk.co.wonderlane.wlpos.entities.cash.SafeSession getSafeSessionValues() {
        if (StringUtils.isNotBlank(extrasJson)) {
            return gsonProvider.gson.fromJson(extrasJson, uk.co.wonderlane.wlpos.entities.cash.SafeSession.class)
        }
        return null
    }
}