package uk.co.wonderlane.wlpos.transactions

class ShiftAudit {

    int id
    int shiftId
    boolean autoGenerated
    String action
    int userId
    String username
    String extras

    static mapping = {
        datasources(["transactions"])

        table "shiftaudit"
        version false

        id column: "id"
        extras column: "extras", type: "uk.co.wonderlane.wlpos.usertypes.JsonType", sqlType: "json"
        shiftId column: "shiftId"
        autoGenerated column: "autoGenerated"
        userId column: "userId"
        username column: "username"
        action column: "action" , sqlType: "enum", enumType: 'string'
    }

}
