package uk.co.wonderlane.wlpos.reporting

enum ReportType {

    PRODUCT_SEARCH,
    PROMOTION_SEARCH,
    SALES_DEPARTMENT,
    SALES_CATEGORY,
    SALES_PRODUCT,
    CATEGORY_SALES,
    SALES,
    PROMOTIONS_GROUPED,
    PROMOTIONS,
    PROMOTION,
    TILL_CONTROL_EVENTS,
    TILL_CONTROL_EVENT,
    PAYPOINT_SALES,
    ORDERS,
    ORDER,
    DELIVERIES,
    DELIVERY,
    DELIVERY_ITEM,
    CATEGORY_SEARCH
}