package uk.co.wonderlane.wlpos.reporting

enum ReportType {

    SALES_DEPARTMENT,
    SALES_CATEGORY,
    SALES_PRODUCT,
    CATEGORY_SALES,
    SALES,
    PROMOTIONS_GROUPED,
    PROMOTIONS,
    PROMOTION,
    TILL_CONTROL_EVENTS,
    TILL_CONTROL_EVENT,
    PAYPOINT_SALES
}