package uk.co.wonderlane.wlpos

import com.google.gson.*
import grails.gorm.transactions.Transactional
import org.joda.time.DateTime
import org.joda.time.format.DateTimeFormat
import org.joda.time.format.DateTimeFormatter
import uk.co.wonderlane.wlpos.dataaccess.DatabaseCredentials
import uk.co.wonderlane.wlpos.dataaccess.MySqlPoolDal
import uk.co.wonderlane.wlpos.entities.cash.FinancialWeek
import uk.co.wonderlane.wlpos.entities.cash.SafeSession
import uk.co.wonderlane.wlpos.entities.cash.SafeSessionAudit
import uk.co.wonderlane.wlpos.enums.SafeSessionAction
import uk.co.wonderlane.wlpos.enums.SafeSessionStatus
import uk.co.wonderlane.wlpos.enums.ShiftAction

import java.sql.*

@Transactional
class SafeManagementService extends MySqlPoolDal {

    def springSecurityService
    def gsonProvider
    def userService

    protected SafeManagementService(DatabaseCredentials databaseCredentials) throws SQLException {
        super(databaseCredentials)
    }

    SafeSession getOpenSafeSession(Integer safeId){
        List<SafeSession> safeSessions = getActiveSafeSession(safeId)
        return safeSessions.stream()
                .filter(session -> SafeSessionStatus.OPEN.equals(session.getSessionStatus()))
                .findFirst()
                .orElse(null)
    }

    SafeSession populateNewSafeSession(int retailerId, int storeId, int safeId, boolean isAutoGenerated) throws Exception {
        int shiftNumber = getLastSessionNumber(retailerId, storeId, safeId) + 1
        FinancialWeek financialWeek = getFinancialWeek(retailerId)
        User loggedInUser = loadLoggedInUser()
        SafeSession safeSession = new SafeSession(retailerId, storeId, safeId)
        safeSession.setSessionNumber(shiftNumber)
        safeSession.setSessionStatus(SafeSessionStatus.OPEN)
        safeSession.setOpenUserId(loggedInUser.getId())
        safeSession.setOpenUsername(loggedInUser.getUsername())
        if (financialWeek != null){
            safeSession.setFinancialWeek(financialWeek)
        }
        saveSafeSession(safeSession) // Save shift
        addAudit(safeSession, SafeSessionAction.OPEN, isAutoGenerated, loggedInUser) // Audit for shift open action
        return safeSession;
    }

     saveSafeSession(SafeSession safeSession) {
        Connection conn = getConnection()
        CallableStatement saveShiftStatement = conn.prepareCall("{ call saveSafeSession(?, ?, ?) }")
        try {
            if (safeSession.id > 0) {
                saveShiftStatement.setInt(1, safeSession.id)
            } else {
                saveShiftStatement.setNull(1, Types.INTEGER)
            }
            saveShiftStatement.setString(2, gsonProvider.gson.toJson(safeSession, SafeSession.class))
            saveShiftStatement.executeUpdate()
            int shiftId = saveShiftStatement.getInt(3)
            safeSession.setId(shiftId) // Update the shift object with the new ID
            return shiftId
        } catch (Exception ex) {
            log.error(String.format("Error persisting safe session for retailer: %d store: %d safeId: %d error: %s", safeSession.getRetailerId(), safeSession.getStoreId(), safeSession.getSafeId(), ex.getMessage()), ex)
            throw new RuntimeException(String.format("Error persisting safe session for retailer: %d store: %d safeId: %d error: %s", safeSession.getRetailerId(), safeSession.getStoreId(), safeSession.getSafeId(), ex.getMessage()), ex)
        } finally{
            saveShiftStatement.close()
            conn.close()
        }
    }

    private getActiveSafeSession(Integer safeId) {
        List<SafeSession> safeSessions = new ArrayList<>()
        Connection conn = getConnection()
        CallableStatement getSafeSessionStatement = conn.prepareCall("{ call getActiveSafeSession(?, ?, ?) }")
        try {
            getSafeSessionStatement.setInt(1, springSecurityService.principal.retailerId)
            if (springSecurityService.principal.storeId != null) {
                getSafeSessionStatement.setInt(2, springSecurityService.principal.storeId)
            } else {
                getSafeSessionStatement.setNull(2, Types.INTEGER)
            }
            if (safeId != null) {
                getSafeSessionStatement.setInt(3, safeId)
            } else {
                getSafeSessionStatement.setNull(3, Types.INTEGER)
            }
            ResultSet rs = getSafeSessionStatement.executeQuery()
            try {
                while (rs.next()) {
                    String sessionJson = rs.getString("session")
                    safeSessions.add(gsonProvider.gson.fromJson(sessionJson, SafeSession.class))
                }
            } finally {
                rs.close()
            }
        }catch (Exception ex) {
            log.error(String.format("Error loading active safe session for retailer: %d safeId: %d error: %s", springSecurityService.principal.retailerId, safeId, ex.getMessage()), ex)
            throw new RuntimeException(String.format("Error loading active safe session for retailer: %d safeId: %d error: %s", springSecurityService.principal.retailerId, safeId, ex.getMessage()), ex)
        } finally {
            getSafeSessionStatement.close()
            conn.close();
        }
        return safeSessions
    }

    private void addAudit(SafeSession safeSession, SafeSessionAction safeSessionAction, boolean isAutoGenerated, User loggedInUser){
        try {
            SafeSessionAudit safeSessionAudit = initializeSafeSessionAudit(safeSession, safeSessionAction, isAutoGenerated, loggedInUser)
            saveSafeSessionAudit(safeSessionAudit)
        } catch (Exception ex) {
            log.error("Error adding audit for shift id: " + safeSession.getId() + " : " + ex.getMessage(), ex)
        }
    }

    private SafeSessionAudit initializeSafeSessionAudit(SafeSession safeSession, SafeSessionAction safeSessionAction, boolean isAutoGenerated, User loggedInUser) {
        SafeSessionAudit safeSessionAudit = new SafeSessionAudit()
        safeSessionAudit.with {
            sessionId = safeSession.id
            autoGenerated = isAutoGenerated
            action = safeSessionAction
            userId = loggedInUser?.id
            username = loggedInUser?.username
            timestamp = new DateTime()
        }

        if (safeSessionAction in [ShiftAction.SPOT_CHECK, ShiftAction.RECONCILE, ShiftAction.RECOUNT, ShiftAction.FINALISE, ShiftAction.ADD_FLOAT, ShiftAction.CASH_LIFT]) {
            JsonObject jsonObject = new JsonObject()

            addJsonFieldToObject(jsonObject, "tenderTotals", safeSession.tenderTotals)

            if (safeSessionAction in [ShiftAction.RECONCILE, ShiftAction.RECOUNT, ShiftAction.FINALISE]) {
                addJsonFieldToObject(jsonObject, "reconciliationTotals", safeSession.reconciliationTotals)
            }

            safeSessionAudit.extras = jsonObject
        }

        return safeSessionAudit
    }

    private void addJsonFieldToObject(JsonObject jsonObject, String key, def value) {
        if (value != null) {
            try {
                String jsonString = gsonProvider?.gson?.toJson(value) ?: "{}"
                JsonElement jsonElement = JsonParser.parseString(jsonString)

                if (jsonElement.isJsonArray()) {
                    jsonObject.add(key, jsonElement.getAsJsonArray())
                } else if (jsonElement.isJsonObject()) {
                    jsonObject.add(key, jsonElement.getAsJsonObject())
                } else {
                    jsonObject.add(key, jsonElement)
                }
            } catch (Exception ex) {
                log.error("Error parsing extra for audit for key: $key : ${ex.message}", ex)
                jsonObject.add(key, new JsonArray())
            }
        } else {
            jsonObject.add(key, JsonNull.INSTANCE)
        }
    }

    private User loadLoggedInUser(){
        int id = springSecurityService.principal.id
        User loggedInUser = userService.getUser(id)
        return loggedInUser
    }

    private Integer getLastSessionNumber(int retailerId, int storeId, int safeId) {
        int result = 0;
        try (Connection conn = getConnection(); CallableStatement getSessionNumberStmt = conn.prepareCall("{ call getPreviousSessionNumberForSafe(?, ?, ?) }")) {
            getSessionNumberStmt.setInt(1, retailerId)
            getSessionNumberStmt.setInt(2, storeId)
            getSessionNumberStmt.setInt(3, safeId)

            try (ResultSet rs = getSessionNumberStmt.executeQuery()) {
                if (rs.next()) {
                    result = rs.getInt("sessionNumber")
                }
            }
        } catch (SQLException ex) {
            log.error(String.format("Sql error loading last safe session number for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, safeId, ex.getMessage()), ex);
            throw new RuntimeException(String.format("Sql error loading last safe session number for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, safeId, ex.getMessage()), ex);
        } catch (Exception ex) {
            log.error(String.format("Unexpected error loading last safe session number for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, safeId, ex.getMessage()), ex);
            throw new RuntimeException(String.format("Unexpected error loading last safe session number for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, safeId, ex.getMessage()), ex);
        }
        return result;
    }

    private FinancialWeek getFinancialWeek(int retailerId){
        FinancialWeek financialWeek =  null
        Date currentDate = convertToSqlDate(new DateTime())
        try (Connection conn = getConnection(); CallableStatement cstmt = conn.prepareCall("{ call getFinancialWeek(?, ?) }")) {
            cstmt.setInt(1, retailerId)
            cstmt.setDate(2, currentDate)
            try (ResultSet rs = cstmt.executeQuery()) {
                if (rs.next()) {
                    financialWeek = new FinancialWeek()
                    financialWeek.setId(rs.getInt("id"))
                    financialWeek.setRetailerId(rs.getInt("retailerId"))
                    financialWeek.setStartDate(rs.getDate("startDate"))
                    financialWeek.setFinancialYear(rs.getString("financialYear"))
                    financialWeek.setWeekNumber(rs.getInt("weekNumber"))
                }
            }
        } catch (SQLException ex) {
            log.error(String.format("Sql error loading financial week from retailer: %d date: %s error: %s", retailerId, currentDate, ex.getMessage()), ex)
        } catch (Exception ex) {
            log.error(String.format("Unexpected error loading financial week from retailer: %d date: %s error: %s", retailerId, currentDate, ex.getMessage()), ex)
        }
        return financialWeek
    }

    private void saveSafeSessionAudit(SafeSessionAudit safeSessionAudit){
        try (Connection conn = getConnection(); CallableStatement saveShiftStatement = conn.prepareCall("{ call saveShiftAudit(?, ?, ?, ?, ?, ?, ?, ?) }")) {
            if (safeSessionAudit.getId() > 0) {
                saveShiftStatement.setInt(1, safeSessionAudit.getId())
            } else {
                saveShiftStatement.setNull(1, Types.INTEGER)
            }
            saveShiftStatement.setInt(2, safeSessionAudit.getSessionId())
            saveShiftStatement.setBoolean(3, safeSessionAudit.isAutoGenerated())
            saveShiftStatement.setString(4, safeSessionAudit.getAction().toString())
            saveShiftStatement.setInt(5, safeSessionAudit.getUserId())
            saveShiftStatement.setString(6, safeSessionAudit.getUsername())
            saveShiftStatement.setTimestamp(7, convertToSqlTimestamp(safeSessionAudit.getTimestamp()))
            saveShiftStatement.setString(8, gsonProvider?.gson?.toJson(safeSessionAudit?.extras) ?: null)
            saveShiftStatement.executeUpdate();
        } catch (SQLException ex) {
            log.error(String.format("Sql error saving safe session audit for safe session id: %s error: %s", safeSessionAudit.getSessionId(), ex.getMessage()), ex)
            throw new RuntimeException(String.format("Sql error saving safe session audit for safe session id: %s error: %s", safeSessionAudit.getSessionId(), ex.getMessage()), ex)
        } catch (Exception ex) {
            log.error(String.format("Unexpected error saving safe session audit for safe session id: %s error: %s", safeSessionAudit.getSessionId(), ex.getMessage()), ex)
            throw new RuntimeException(String.format("Unexpected error saving safe session audit for shift id: %s error: %s", safeSessionAudit.getSessionId(), ex.getMessage()), ex)
        }
    }

    private  Date convertToSqlDate(DateTime date) {
        return new Date(date.withTimeAtStartOfDay().getMillis());
    }

    private String convertDateTimeToString(DateTime dateTime) {
        if(dateTime == null) {
            return null;
        }
        DateTimeFormatter formatter = DateTimeFormat.forPattern(DATE_PATTERN_YYYYMMDD_HHMMSS);
        return dateTime.toString(formatter);
    }

    private Timestamp convertToSqlTimestamp(DateTime dateTime) {
        if (dateTime != null){
            return new Timestamp(dateTime.getMillis());
        }
        return new Timestamp(new DateTime().getMillis());
    }
}
