package uk.co.wonderlane.wlpos

import com.google.gson.*
import grails.gorm.transactions.Transactional
import org.joda.time.DateTime
import org.joda.time.format.DateTimeFormat
import org.joda.time.format.DateTimeFormatter
import uk.co.wonderlane.wlpos.dataaccess.DatabaseCredentials
import uk.co.wonderlane.wlpos.dataaccess.MySqlPoolDal
import uk.co.wonderlane.wlpos.entities.cash.FinancialWeek
import uk.co.wonderlane.wlpos.entities.cash.SafeSession
import uk.co.wonderlane.wlpos.entities.cash.SafeSessionAudit
import uk.co.wonderlane.wlpos.enums.SafeSessionAction
import uk.co.wonderlane.wlpos.enums.SafeSessionStatus
import uk.co.wonderlane.wlpos.enums.ShiftAction

import java.sql.*

@Transactional
class SafeManagementService extends MySqlPoolDal {

    def springSecurityService
    def gsonProvider
    def userService
    def commonService
    def financialWeekService

    protected SafeManagementService(DatabaseCredentials databaseCredentials) throws SQLException {
        super(databaseCredentials)
    }

    SafeSession getOpenSafeSession(Integer safeId){
        List<SafeSession> safeSessions = getActiveSafeSession(safeId)
        return safeSessions.stream()
                .filter(session -> SafeSessionStatus.OPEN.equals(session.getSessionStatus()))
                .findFirst()
                .orElse(null)
    }

    SafeSession createNewSafeSession(int retailerId, int storeId, int safeId, boolean isAutoGenerated){
        SafeSession safeSession = getOpenSafeSession(safeId)
        if (safeSession == null) {
            safeSession = populateNewSafeSession(retailerId, storeId, safeId, isAutoGenerated)
        }
        return safeSession
    }

     def saveSafeSession(SafeSession safeSession) {
        Connection conn = getConnection()
        CallableStatement saveSafeSessionStatement = conn.prepareCall("{ call saveSafeSession(?, ?, ?) }")
        try {
            if (safeSession.id > 0) {
                saveSafeSessionStatement.setInt(1, safeSession.id)
            } else {
                saveSafeSessionStatement.setNull(1, Types.INTEGER)
            }
            saveSafeSessionStatement.setString(2, gsonProvider.gson.toJson(safeSession, SafeSession.class))
            saveSafeSessionStatement.executeUpdate()
            int shiftId = saveSafeSessionStatement.getInt(3)
            safeSession.setId(shiftId) // Update the shift object with the new ID
            return shiftId
        } catch (Exception ex) {
            log.error("Error persisting safe session for retailer: ${safeSession.getRetailerId()} store: ${safeSession.getStoreId()} safeId: ${safeSession.getSafeId()} error: ${ex.getMessage()}", ex)
            throw new RuntimeException("Error persisting safe session for retailer: ${safeSession.getRetailerId()} store: ${safeSession.getStoreId()} safeId: ${safeSession.getSafeId()} error: ${ex.getMessage()}", ex)
        } finally{
            saveSafeSessionStatement.close()
            conn.close()
        }
    }

    private SafeSession populateNewSafeSession(int retailerId, int storeId, int safeId, boolean isAutoGenerated) throws Exception {
        int shiftNumber = getLastSessionNumber(retailerId, storeId, safeId) + 1
        FinancialWeek financialWeek = financialWeekService.getFinancialWeek(retailerId)
        User loggedInUser = loadLoggedInUser()
        SafeSession safeSession = new SafeSession(retailerId, storeId, safeId)
        safeSession.setSessionNumber(shiftNumber)
        safeSession.setSessionStatus(SafeSessionStatus.OPEN)
        safeSession.setOpenUserId(loggedInUser.getId())
        safeSession.setOpenUsername(loggedInUser.getUsername())
        safeSession.setOpenTime(commonService.convertDateTimeToString(new DateTime()))
        if (financialWeek != null){
            safeSession.setFinancialWeek(financialWeek)
        }
        saveSafeSession(safeSession) // Save shift
        addAudit(safeSession, SafeSessionAction.OPEN, isAutoGenerated, loggedInUser) // Audit for shift open action
        return safeSession;
    }

    List<SafeSession> getActiveSafeSession(Integer safeId) {
        List<SafeSession> safeSessions = new ArrayList<>()
        Connection conn = getConnection()
        CallableStatement activeSafeSessionStatement = conn.prepareCall("{ call getActiveSafeSession(?, ?, ?) }")
        try {
            activeSafeSessionStatement.setInt(1, springSecurityService.principal.retailerId)
            if (springSecurityService.principal.storeId != null) {
                activeSafeSessionStatement.setInt(2, springSecurityService.principal.storeId)
            } else {
                activeSafeSessionStatement.setNull(2, Types.INTEGER)
            }
            if (safeId != null) {
                activeSafeSessionStatement.setInt(3, safeId)
            } else {
                activeSafeSessionStatement.setNull(3, Types.INTEGER)
            }
            ResultSet rs = activeSafeSessionStatement.executeQuery()
            try {
                while (rs.next()) {
                    String sessionJson = rs.getString("session")
                    safeSessions.add(gsonProvider.gson.fromJson(sessionJson, SafeSession.class))
                }
            } finally {
                rs.close()
            }
        }catch (Exception ex) {
            log.error("Error loading active safe session for retailer: ${springSecurityService.principal.retailerId} safeId: ${safeId} error: ${ex.getMessage()}", ex)
            throw new RuntimeException("Error loading active safe session for retailer: ${springSecurityService.principal.retailerId} safeId: ${safeId} error: ${ex.getMessage()}", ex)
        } finally {
            activeSafeSessionStatement.close()
            conn.close();
        }
        return safeSessions
    }

    private void addAudit(SafeSession safeSession, SafeSessionAction safeSessionAction, boolean isAutoGenerated, User loggedInUser){
        try {
            SafeSessionAudit safeSessionAudit = initializeSafeSessionAudit(safeSession, safeSessionAction, isAutoGenerated, loggedInUser)
            saveSafeSessionAudit(safeSessionAudit)
        } catch (Exception ex) {
            log.error("Error adding audit for shift id: ${safeSession.getId()}, error ${ex.getMessage()} ", ex)
        }
    }

    private SafeSessionAudit initializeSafeSessionAudit(SafeSession safeSession, SafeSessionAction safeSessionAction, boolean isAutoGenerated, User loggedInUser) {
        SafeSessionAudit safeSessionAudit = new SafeSessionAudit()
        safeSessionAudit.with {
            sessionId = safeSession.id
            autoGenerated = isAutoGenerated
            action = safeSessionAction
            userId = loggedInUser?.id
            username = loggedInUser?.username
            timestamp = new DateTime()
        }

        if (safeSessionAction in [ShiftAction.SPOT_CHECK, ShiftAction.RECONCILE, ShiftAction.RECOUNT, ShiftAction.FINALISE, ShiftAction.ADD_FLOAT, ShiftAction.CASH_LIFT]) {
            JsonObject jsonObject = new JsonObject()

            addJsonFieldToObject(jsonObject, "tenderTotals", safeSession.tenderTotals)

            if (safeSessionAction in [ShiftAction.RECONCILE, ShiftAction.RECOUNT, ShiftAction.FINALISE]) {
                addJsonFieldToObject(jsonObject, "reconciliationTotals", safeSession.reconciliationTotals)
            }

            safeSessionAudit.extras = jsonObject
        }

        return safeSessionAudit
    }

    private void addJsonFieldToObject(JsonObject jsonObject, String key, def value) {
        if (value != null) {
            try {
                String jsonString = gsonProvider?.gson?.toJson(value) ?: "{}"
                JsonElement jsonElement = JsonParser.parseString(jsonString)

                if (jsonElement.isJsonArray()) {
                    jsonObject.add(key, jsonElement.getAsJsonArray())
                } else if (jsonElement.isJsonObject()) {
                    jsonObject.add(key, jsonElement.getAsJsonObject())
                } else {
                    jsonObject.add(key, jsonElement)
                }
            } catch (Exception ex) {
                log.error("Error parsing extra for audit for key: $key : ${ex.message}", ex)
                jsonObject.add(key, new JsonArray())
            }
        } else {
            jsonObject.add(key, JsonNull.INSTANCE)
        }
    }

    private User loadLoggedInUser(){
        int id = springSecurityService.principal.id
        User loggedInUser = userService.getUser(id)
        return loggedInUser
    }

    private Integer getLastSessionNumber(int retailerId, int storeId, int safeId) {
        int result = 0;
        try (Connection conn = getConnection(); CallableStatement getSessionNumberStmt = conn.prepareCall("{ call getPreviousSessionNumberForSafe(?, ?, ?) }")) {
            getSessionNumberStmt.setInt(1, retailerId)
            getSessionNumberStmt.setInt(2, storeId)
            getSessionNumberStmt.setInt(3, safeId)

            try (ResultSet rs = getSessionNumberStmt.executeQuery()) {
                if (rs.next()) {
                    result = rs.getInt("sessionNumber")
                }
            }
        } catch (SQLException ex) {
            log.error("Sql error loading last safe session number for from retailer: ${retailerId} store: ${storeId} safeId: ${safeId} error: ${ex.getMessage()}", ex);
            throw new RuntimeException("Sql error loading last safe session number for from retailer: ${retailerId} store: ${storeId} tillId: ${safeId} error: ${ex.getMessage()}", ex);
        } catch (Exception ex) {
            log.error("Unexpected error loading last safe session number for from retailer: ${retailerId} store: ${storeId} safeId: ${safeId} error: ${ex.getMessage()}", ex);
            throw new RuntimeException("Unexpected error loading last safe session number for from retailer: ${retailerId} store: ${storeId} safeId: ${safeId} error: ${ex.getMessage()}", ex);
        }
        return result;
    }


    private void saveSafeSessionAudit(SafeSessionAudit safeSessionAudit){
        try (Connection conn = getConnection(); CallableStatement saveSafeSessionStatement = conn.prepareCall("{ call saveSafeSessionAudit(?, ?, ?, ?, ?, ?, ?, ?) }")) {
            if (safeSessionAudit.getId() > 0) {
                saveSafeSessionStatement.setInt(1, safeSessionAudit.getId())
            } else {
                saveSafeSessionStatement.setNull(1, Types.INTEGER)
            }
            saveSafeSessionStatement.setInt(2, safeSessionAudit.getSessionId())
            saveSafeSessionStatement.setBoolean(3, safeSessionAudit.isAutoGenerated())
            saveSafeSessionStatement.setString(4, safeSessionAudit.getAction().toString())
            saveSafeSessionStatement.setInt(5, safeSessionAudit.getUserId())
            saveSafeSessionStatement.setString(6, safeSessionAudit.getUsername())
            saveSafeSessionStatement.setTimestamp(7, commonService.convertToSqlTimestamp(safeSessionAudit.getTimestamp()))
            saveSafeSessionStatement.setString(8, gsonProvider?.gson?.toJson(safeSessionAudit?.extras) ?: null)
            saveSafeSessionStatement.executeUpdate();
        } catch (SQLException ex) {
            log.error("Sql error saving safe session audit for safe session id: ${safeSessionAudit.getSessionId()} error: ${ex.getMessage()}", ex)
            throw new RuntimeException("Sql error saving safe session audit for safe session id: ${safeSessionAudit.getSessionId()} error: ${ex.getMessage()}", ex)
        } catch (Exception ex) {
            log.error("Unexpected error saving safe session audit for safe session id: ${safeSessionAudit.getSessionId()} error: ${ex.getMessage()}", ex)
            throw new RuntimeException("Unexpected error saving safe session audit for safe session id: ${safeSessionAudit.getSessionId()} error: ${ex.getMessage()}", ex)
        }
    }
}
