package uk.co.wonderlane.wlpos

import com.google.gson.*
import grails.gorm.transactions.Transactional
import org.joda.time.DateTime
import uk.co.wonderlane.wlpos.dataaccess.DatabaseCredentials
import uk.co.wonderlane.wlpos.dataaccess.MySqlPoolDal
import uk.co.wonderlane.wlpos.entities.cash.FinancialWeek
import uk.co.wonderlane.wlpos.entities.cash.ReconciliationTotal
import uk.co.wonderlane.wlpos.entities.cash.SafeSession
import uk.co.wonderlane.wlpos.entities.cash.SafeSessionAudit
import uk.co.wonderlane.wlpos.entities.cashmanagement.CashManagementConfig
import uk.co.wonderlane.wlpos.enums.SafeSessionAction
import uk.co.wonderlane.wlpos.enums.SafeSessionStatus
import uk.co.wonderlane.wlpos.enums.TenderType

import java.sql.*

@Transactional
class SafeManagementService extends MySqlPoolDal {

    def springSecurityService
    def gsonProvider
    def userService
    def commonService
    def financialWeekService
    def cashManagementService

    protected SafeManagementService(DatabaseCredentials databaseCredentials) throws SQLException {
        super(databaseCredentials)
    }

    SafeSession getOpenSafeSession(Integer safeId){
        List<SafeSession> safeSessions = getActiveSafeSession(safeId)
        return safeSessions.stream()
                .filter(session -> SafeSessionStatus.OPEN.equals(session.getSessionStatus()))
                .findFirst()
                .orElse(null)
    }

    SafeSession createNewSafeSession(int retailerId, int storeId, int safeId, boolean isAutoGenerated){
        SafeSession safeSession = getOpenSafeSession(safeId)
        if (safeSession == null) {
            safeSession = populateNewSafeSession(retailerId, storeId, safeId, isAutoGenerated)
        }
        return safeSession
    }

     def saveSafeSession(SafeSession safeSession) {
        Connection conn = getConnection()
        CallableStatement saveSafeSessionStatement = conn.prepareCall("{ call saveSafeSession(?, ?, ?) }")
        try {
            if (safeSession.id > 0) {
                saveSafeSessionStatement.setInt(1, safeSession.id)
            } else {
                saveSafeSessionStatement.setNull(1, Types.INTEGER)
            }
            saveSafeSessionStatement.setString(2, gsonProvider.gson.toJson(safeSession, SafeSession.class))
            saveSafeSessionStatement.executeUpdate()
            int sessionId = saveSafeSessionStatement.getInt(3)
            safeSession.setId(sessionId) // Update the safe session object with the new ID
            return sessionId
        } catch (Exception ex) {
            log.error("Error persisting safe session for retailer: ${safeSession.getRetailerId()} store: ${safeSession.getStoreId()} safeId: ${safeSession.getSafeId()} error: ${ex.getMessage()}", ex)
            throw new RuntimeException("Error persisting safe session for retailer: ${safeSession.getRetailerId()} store: ${safeSession.getStoreId()} safeId: ${safeSession.getSafeId()} error: ${ex.getMessage()}", ex)
        } finally{
            saveSafeSessionStatement.close()
            conn.close()
        }
    }

    private SafeSession populateNewSafeSession(int retailerId, int storeId, int safeId, boolean isAutoGenerated) throws Exception {
        int sessionNumber = getLastSessionNumber(retailerId, storeId, safeId) + 1
        FinancialWeek financialWeek = financialWeekService.getFinancialWeek(retailerId)
        User loggedInUser = loadLoggedInUser()
        SafeSession safeSession = new SafeSession(retailerId, storeId, safeId)
        safeSession.setSessionNumber(sessionNumber)
        safeSession.setSessionStatus(SafeSessionStatus.OPEN)
        safeSession.setOpenUserId(loggedInUser.getId())
        safeSession.setOpenUsername(loggedInUser.getUsername())
        safeSession.setOpenTime(commonService.convertDateTimeToString(new DateTime()))
        if (financialWeek != null){
            safeSession.setFinancialWeek(financialWeek)
        }
        saveSafeSession(safeSession) // Save session
        addAudit(safeSession, SafeSessionAction.OPEN, isAutoGenerated, loggedInUser) // Audit for session open action
        return safeSession;
    }

    List<SafeSession> getActiveSafeSession(Integer safeId) {
        List<SafeSession> safeSessions = new ArrayList<>()
        Connection conn = getConnection()
        CallableStatement activeSafeSessionStatement = conn.prepareCall("{ call getActiveSafeSession(?, ?, ?) }")
        try {
            activeSafeSessionStatement.setInt(1, springSecurityService.principal.retailerId)
            if (springSecurityService.principal.storeId != null) {
                activeSafeSessionStatement.setInt(2, springSecurityService.principal.storeId)
            } else {
                activeSafeSessionStatement.setNull(2, Types.INTEGER)
            }
            if (safeId != null) {
                activeSafeSessionStatement.setInt(3, safeId)
            } else {
                activeSafeSessionStatement.setNull(3, Types.INTEGER)
            }
            ResultSet rs = activeSafeSessionStatement.executeQuery()
            try {
                while (rs.next()) {
                    String sessionJson = rs.getString("session")
                    safeSessions.add(gsonProvider.gson.fromJson(sessionJson, SafeSession.class))
                }
            } finally {
                rs.close()
            }
        }catch (Exception ex) {
            log.error("Error loading active safe session for retailer: ${springSecurityService.principal.retailerId} safeId: ${safeId} error: ${ex.getMessage()}", ex)
            throw new RuntimeException("Error loading active safe session for retailer: ${springSecurityService.principal.retailerId} safeId: ${safeId} error: ${ex.getMessage()}", ex)
        } finally {
            activeSafeSessionStatement.close()
            conn.close();
        }
        return safeSessions
    }

    private void addAudit(SafeSession safeSession, SafeSessionAction safeSessionAction, boolean isAutoGenerated, User loggedInUser){
        try {
            SafeSessionAudit safeSessionAudit = initializeSafeSessionAudit(safeSession, safeSessionAction, isAutoGenerated, loggedInUser)
            saveSafeSessionAudit(safeSessionAudit)
        } catch (Exception ex) {
            log.error("Error adding audit for session id: ${safeSession.getId()}, error ${ex.getMessage()} ", ex)
        }
    }

    private SafeSessionAudit initializeSafeSessionAudit(SafeSession safeSession, SafeSessionAction safeSessionAction, boolean isAutoGenerated, User loggedInUser) {
        SafeSessionAudit safeSessionAudit = new SafeSessionAudit()
        safeSessionAudit.with {
            sessionId = safeSession.id
            autoGenerated = isAutoGenerated
            action = safeSessionAction
            userId = loggedInUser?.id
            username = loggedInUser?.username
            timestamp = new DateTime()
        }

        if (safeSessionAction in [SafeSessionAction.SPOT_CHECK, SafeSessionAction.RECONCILE, SafeSessionAction.RECOUNT, SafeSessionAction.FINALISE]) {
            JsonObject jsonObject = new JsonObject()

            addJsonFieldToObject(jsonObject, "tenderTotals", safeSession.tenderTotals)

            if (safeSessionAction in [SafeSessionAction.RECONCILE, SafeSessionAction.RECOUNT, SafeSessionAction.FINALISE]) {
                addJsonFieldToObject(jsonObject, "reconciliationTotals", safeSession.reconciliationTotals)
            }

            safeSessionAudit.extras = jsonObject
        }

        return safeSessionAudit
    }

    private void addJsonFieldToObject(JsonObject jsonObject, String key, def value) {
        if (value != null) {
            try {
                String jsonString = gsonProvider?.gson?.toJson(value) ?: "{}"
                JsonElement jsonElement = JsonParser.parseString(jsonString)

                if (jsonElement.isJsonArray()) {
                    jsonObject.add(key, jsonElement.getAsJsonArray())
                } else if (jsonElement.isJsonObject()) {
                    jsonObject.add(key, jsonElement.getAsJsonObject())
                } else {
                    jsonObject.add(key, jsonElement)
                }
            } catch (Exception ex) {
                log.error("Error parsing extra for audit for key: $key : ${ex.message}", ex)
                jsonObject.add(key, new JsonArray())
            }
        } else {
            jsonObject.add(key, JsonNull.INSTANCE)
        }
    }

    private User loadLoggedInUser(){
        int id = springSecurityService.principal.id
        User loggedInUser = userService.getUser(id)
        return loggedInUser
    }

    private Integer getLastSessionNumber(int retailerId, int storeId, int safeId) {
        int result = 0;
        try (Connection conn = getConnection(); CallableStatement getSessionNumberStmt = conn.prepareCall("{ call getPreviousSessionNumberForSafe(?, ?, ?) }")) {
            getSessionNumberStmt.setInt(1, retailerId)
            getSessionNumberStmt.setInt(2, storeId)
            getSessionNumberStmt.setInt(3, safeId)

            try (ResultSet rs = getSessionNumberStmt.executeQuery()) {
                if (rs.next()) {
                    result = rs.getInt("sessionNumber")
                }
            }
        } catch (SQLException ex) {
            log.error("Sql error loading last safe session number for from retailer: ${retailerId} store: ${storeId} safeId: ${safeId} error: ${ex.getMessage()}", ex);
            throw new RuntimeException("Sql error loading last safe session number for from retailer: ${retailerId} store: ${storeId} tillId: ${safeId} error: ${ex.getMessage()}", ex);
        } catch (Exception ex) {
            log.error("Unexpected error loading last safe session number for from retailer: ${retailerId} store: ${storeId} safeId: ${safeId} error: ${ex.getMessage()}", ex);
            throw new RuntimeException("Unexpected error loading last safe session number for from retailer: ${retailerId} store: ${storeId} safeId: ${safeId} error: ${ex.getMessage()}", ex);
        }
        return result;
    }


    private void saveSafeSessionAudit(SafeSessionAudit safeSessionAudit){
        try (Connection conn = getConnection(); CallableStatement saveSafeSessionStatement = conn.prepareCall("{ call saveSafeSessionAudit(?, ?, ?, ?, ?, ?, ?, ?) }")) {
            if (safeSessionAudit.getId() > 0) {
                saveSafeSessionStatement.setInt(1, safeSessionAudit.getId())
            } else {
                saveSafeSessionStatement.setNull(1, Types.INTEGER)
            }
            saveSafeSessionStatement.setInt(2, safeSessionAudit.getSessionId())
            saveSafeSessionStatement.setBoolean(3, safeSessionAudit.isAutoGenerated())
            saveSafeSessionStatement.setString(4, safeSessionAudit.getAction().toString())
            saveSafeSessionStatement.setInt(5, safeSessionAudit.getUserId())
            saveSafeSessionStatement.setString(6, safeSessionAudit.getUsername())
            saveSafeSessionStatement.setTimestamp(7, commonService.convertToSqlTimestamp(safeSessionAudit.getTimestamp()))
            saveSafeSessionStatement.setString(8, gsonProvider?.gson?.toJson(safeSessionAudit?.extras) ?: null)
            saveSafeSessionStatement.executeUpdate();
        } catch (SQLException ex) {
            log.error("Sql error saving safe session audit for safe session id: ${safeSessionAudit.getSessionId()} error: ${ex.getMessage()}", ex)
            throw new RuntimeException("Sql error saving safe session audit for safe session id: ${safeSessionAudit.getSessionId()} error: ${ex.getMessage()}", ex)
        } catch (Exception ex) {
            log.error("Unexpected error saving safe session audit for safe session id: ${safeSessionAudit.getSessionId()} error: ${ex.getMessage()}", ex)
            throw new RuntimeException("Unexpected error saving safe session audit for safe session id: ${safeSessionAudit.getSessionId()} error: ${ex.getMessage()}", ex)
        }
    }

    def getSafeSession(int safeSessionId) {
        Connection conn = getConnection()
        CallableStatement getSafeSessionStatement = conn.prepareCall("{ call getSafeSession(?, ?, ?) }")
        try {
            getSafeSessionStatement.setInt(1, springSecurityService.principal.retailerId)
            getSafeSessionStatement.setInt(2, springSecurityService.principal.storeId)
            getSafeSessionStatement.setInt(3, safeSessionId)
            ResultSet rs = getSafeSessionStatement.executeQuery()
            try {
                if (rs.next()) {
                    String safeSessionJson = rs.getString("session")
                    return gsonProvider.gson.fromJson(safeSessionJson, SafeSession.class)
                }
            } finally {
                rs.close()
            }
        }catch (Exception ex) {
            log.error("Error loading safe session for from retailer: ${springSecurityService.principal.retailerId} store: ${springSecurityService.principal.storeId} safe SessionId: ${safeSessionId} " + "error: ${ex.getMessage()}", ex)
            throw new RuntimeException("Error loading safe session for from retailer: ${springSecurityService.principal.retailerId} store: ${springSecurityService.principal.storeId} safe SessionId: ${safeSessionId} " + "error: ${ex.getMessage()}", ex)
        } finally {
            getSafeSessionStatement.close()
            conn.close()
        }

        return null
    }

    void processSafeSessionPendingTenderSave(SafeSessionCashUpCommand safeSessionCashUpCommand, SafeSession safeSession){
        try {
            updatePendingCashTotal(safeSessionCashUpCommand, safeSession) //This will update pending cash attribute on session object for temporary
            updatePendingVoucherTotal(safeSessionCashUpCommand, safeSession) //This will update pending voucher attribute on session object for temporary
            saveSafeSession(safeSession) //This will called session save method to process on hold cash and voucher values
        } catch (Exception ex) {
            log.error("Error closing safe session for retailer id: ${safeSession.getRetailerId()} store id: ${safeSession.getRetailerId()} safe id: ${safeSession.getSafeId()} error: ${ex.getMessage()}", ex)
            throw new RuntimeException("Error closing safe session for retailer id: ${safeSession.getRetailerId()} store id: ${safeSession.getRetailerId()} safe id: ${safeSession.getSafeId()} error: ${ex.getMessage()}", ex)
        }
    }

    void processSafeSessionDataSave(SafeSessionSaveCommand safeSessionSaveCommand, SafeSession safeSession){
        try {
            User loggedInUser = loadLoggedInUser()
            // This method will populate session data corresponding at action requested
            // Based on request (reconcile, recount or finalise) session object is populated differently
            updateSafeSessionSaveFields(safeSessionSaveCommand, safeSession, loggedInUser)
            saveSafeSession(safeSession) //This will called session save method to process close
            SafeSessionAction auditSafeSessionAction = safeSessionSaveCommand.isRecount ? SafeSessionAction.RECOUNT : safeSessionSaveCommand.isFinalise ? SafeSessionAction.FINALISE : SafeSessionAction.RECONCILE
            addAudit(safeSession, auditSafeSessionAction, false, loggedInUser)
        } catch (Exception ex) {
            log.error("Error processing safe session summary for retailer id: ${safeSession.retailerId} store id: ${safeSession.storeId} session id: ${safeSession.id} error: ${ex.getMessage()}", ex)
            throw new RuntimeException("Error processing safe session summary for retailer id: ${safeSession.retailerId} store id: ${safeSession.storeId} session id: ${safeSession.id} error: ${ex.getMessage()}", ex)
        }
    }

    private void updateSafeSessionSaveFields(SafeSessionSaveCommand safeSessionSaveCommand, SafeSession safeSession, User loggedInUser){
        if (safeSession.sessionStatus == SafeSessionStatus.OPEN || safeSession.sessionStatus == SafeSessionStatus.RECONCILED){
            if (!safeSessionSaveCommand.isFinalise){
                // If the request is not a final request (Intermediate --> reconcile or recount)
                // Then should
                //   1. Move on hold cash values into session cash value
                //   2. Move on hold voucher values into session voucher value
                //   3. Update variance reason and reason text
                updatePendingToCashTotal(safeSession) // Update on hold cash into actual session object cash
                updatePendingToVoucherTotal(safeSession) // Update on hold voucher into actual session object voucher
                if (safeSessionSaveCommand.tenderReconciliationVarianceReason != null) { // Update variance and variance text
                    safeSession.reconciliationTotals.findAll { it.variance != BigDecimal.ZERO }?.each {
                        it.varianceReason = safeSessionSaveCommand.tenderReconciliationVarianceReason
                        it.varianceReasonText = safeSessionSaveCommand.tenderReconciliationVarianceReasonText
                    }
                }

                if(!safeSessionSaveCommand.isRecount) {
                    safeSession.reconciledDate = DateTime.now()
                    safeSession.reconciledByUserId = loggedInUser.getId()
                    safeSession.reconciledByUsersName = loggedInUser.getUsername()
                    safeSession.sessionStatus = SafeSessionStatus.RECONCILED
                } else {
                    //Handle recount here
                }
                // Once update done clear `pending` list
                safeSession.getPendingReconciliationTotals().clear()
            } else {
                safeSession.sessionStatus = SafeSessionStatus.FINALISED
            }
        }
    }

    private void updatePendingToCashTotal(SafeSession safeSession) {
        //Load on hold cash total values --> Saved at cash up view
        def cashPendingTotal = safeSession.pendingReconciliationTotals.find { it.tenderType == TenderType.CASH }

        //Then update pending cash value to session actual cash value
        def cashTotal = safeSession.reconciliationTotals.find { it.tenderType == TenderType.CASH } ?:
                new ReconciliationTotal(TenderType.CASH).tap { safeSession.reconciliationTotals << it }
        cashTotal.value = cashPendingTotal?.value ?: BigDecimal.ZERO
        cashTotal.variance = cashPendingTotal?.variance ?: BigDecimal.ZERO
    }

    private void updatePendingToVoucherTotal(SafeSession safeSession) {
        //Load on hold voucher total values --> Saved at cash up view
        def vouchersPendingTotal = safeSession.pendingReconciliationTotals.find { it.tenderType == TenderType.VOUCHER }

        //Then update pending voucher value to session actual voucher value
        def vouchersTotal = safeSession.reconciliationTotals.find { it.tenderType == TenderType.VOUCHER } ?:
                new ReconciliationTotal(TenderType.VOUCHER).tap { safeSession.reconciliationTotals << it }
        vouchersTotal.value = vouchersPendingTotal?.value ?: BigDecimal.ZERO
        vouchersTotal.variance = vouchersPendingTotal?.variance ?: BigDecimal.ZERO
    }

    private void updatePendingCashTotal(SafeSessionCashUpCommand safeSessionCashUpCommand, SafeSession safeSession) {
        def cashTotal = safeSession.pendingReconciliationTotals.find { it.tenderType == TenderType.CASH } ?:
                new ReconciliationTotal(TenderType.CASH).tap { safeSession.pendingReconciliationTotals << it }
        cashTotal.value = calculateCashTotal(safeSessionCashUpCommand)
        BigDecimal currentCashTotal = (cashTotal.value ?: BigDecimal.ZERO)
        BigDecimal currentTenderTotal = (safeSession.tenderTotals.findAll { it.tenderType == TenderType.VOUCHER }*.value.sum() ?: BigDecimal.ZERO) as BigDecimal
        cashTotal.variance = currentCashTotal.subtract(currentTenderTotal)
    }

    private void updatePendingVoucherTotal(SafeSessionCashUpCommand safeSessionCashUpCommand, SafeSession safeSession) {
        def vouchersTotal = safeSession.pendingReconciliationTotals.find { it.tenderType == TenderType.VOUCHER } ?:
                new ReconciliationTotal(TenderType.VOUCHER).tap { safeSession.pendingReconciliationTotals << it }
        vouchersTotal.value = safeSessionCashUpCommand.vouchersTotal
        BigDecimal currentVoucherTotal = (vouchersTotal.value ?: BigDecimal.ZERO)
        BigDecimal currentTenderTotal = (safeSession.tenderTotals.findAll { it.tenderType == TenderType.VOUCHER }*.value.sum() ?: BigDecimal.ZERO) as BigDecimal
        vouchersTotal.variance = currentVoucherTotal.subtract(currentTenderTotal)
    }

    private BigDecimal calculateCashTotal(SafeSessionCashUpCommand safeSessionCashUpCommand) {
        switch(safeSessionCashUpCommand.cashUpBy) {
            case "VALUE":
                return sumDenominations(safeSessionCashUpCommand)
            case "DENOMINATION":
                return sumDenominationsWithMultipliers(safeSessionCashUpCommand)
            default:
                return safeSessionCashUpCommand.cashTotal
        }
    }

    private BigDecimal sumDenominations(SafeSessionCashUpCommand cmd) {
        ([cmd.fiftyPounds, cmd.twentyPounds, cmd.tenPounds, cmd.fivePounds, cmd.twoPounds, cmd.onePounds, cmd.fiftyPences, cmd.twentyPences, cmd.tenPences,
          cmd.fivePences, cmd.twoPences, cmd.onePences].sum() ?: 0) as BigDecimal
    }

    private BigDecimal sumDenominationsWithMultipliers(SafeSessionCashUpCommand cmd) {
        ([cmd.fiftyPounds * 50, cmd.twentyPounds * 20, cmd.tenPounds * 10, cmd.fivePounds * 5, cmd.twoPounds * 2, cmd.onePounds, cmd.fiftyPences * 0.50, cmd.twentyPences * 0.20,
          cmd.tenPences * 0.10, cmd.fivePences * 0.05, cmd.twoPences * 0.02, cmd.onePences * 0.01].sum() ?: 0) as BigDecimal
    }

    int getConfiguredRecountAttempts(){
        try {
            CashManagementConfig cashManagementConfig = cashManagementService.getCashManagementConfig(springSecurityService.principal.retailerId, springSecurityService.principal.storeId)
            if (cashManagementConfig != null) {
                return cashManagementConfig.getSafeRecountLimit()
            }
            return -1
        } catch (Exception ex) {
            log.error("Error loading cash management configuration for retailer id: ${springSecurityService.principal.retailerId} store id: ${springSecurityService.principal.storeId} error: ${ex.getMessage()}", ex)
            throw new RuntimeException("Error loading cash management configuration for retailer id: ${springSecurityService.principal.retailerId} store id: ${springSecurityService.principal.storeId} error: ${ex.getMessage()}", ex)
        }
    }



}

