package uk.co.wonderlane.wlpos

import grails.gorm.transactions.Transactional
import org.joda.time.DateTime
import org.joda.time.format.DateTimeFormat
import org.joda.time.format.DateTimeFormatter
import uk.co.wonderlane.wlpos.dataaccess.DatabaseCredentials
import uk.co.wonderlane.wlpos.dataaccess.MySqlDal
import uk.co.wonderlane.wlpos.entities.cash.Shift
import uk.co.wonderlane.wlpos.entities.transaction.FinancialWeek
import uk.co.wonderlane.wlpos.entities.transaction.ShiftAudit
import uk.co.wonderlane.wlpos.entities.transaction.Transaction
import uk.co.wonderlane.wlpos.enums.ShiftAction
import uk.co.wonderlane.wlpos.enums.ShiftStatus

import java.sql.CallableStatement
import java.sql.Connection
import java.sql.Date
import java.sql.ResultSet
import java.sql.SQLException
import java.sql.Timestamp
import java.sql.Types
import java.util.stream.Collectors

@Transactional
class ShiftService extends MySqlDal {

    def springSecurityService
    def gsonProvider
    def storeService
    def userService

    protected static final String DATE_FORMAT = "yyyy-MM-dd";
    public static String DATE_PATTERN_YYYYMMDD_HHMMSS = "yyyy-MM-dd HH:mm:ss";

    ShiftService(DatabaseCredentials databaseCredentials) {
        super(databaseCredentials)
    }

    def getShifts(Integer tillId) {
        List<Shift> shifts = new ArrayList<>()

        Connection conn = getConnection()
        CallableStatement getShiftsStatement = conn.prepareCall("{ call getActiveShifts(?, ?, ?) }")

        try {
            getShiftsStatement.setInt(1, springSecurityService.principal.retailerId)
            if (springSecurityService.principal.storeId != null) {
                getShiftsStatement.setInt(2, springSecurityService.principal.storeId)
            } else {
                getShiftsStatement.setNull(2, Types.INTEGER)
            }

            if (tillId != null) {
                getShiftsStatement.setInt(3, tillId)
            } else {
                getShiftsStatement.setNull(3, Types.INTEGER)
            }

            ResultSet rs = getShiftsStatement.executeQuery()

            try {
                while (rs.next()) {
                    String shiftJson = rs.getString("shift")

                    shifts.add(gsonProvider.gson.fromJson(shiftJson, Shift.class))
                }
            } finally {
                rs.close()
            }
        } finally {
            getShiftsStatement.close()
            conn.close();
        }

        return shifts
    }

    def getShift(int shiftId) {
        Connection conn = getConnection()
        CallableStatement getShiftStatement = conn.prepareCall("{ call getShift(?, ?, ?) }")

        try {
            getShiftStatement.setInt(1, springSecurityService.principal.retailerId)
            getShiftStatement.setInt(2, springSecurityService.principal.storeId)
            getShiftStatement.setInt(3, shiftId)

            ResultSet rs = getShiftStatement.executeQuery()

            try {
                if (rs.next()) {
                    String shiftJson = rs.getString("shift")

                    return gsonProvider.gson.fromJson(shiftJson, Shift.class)
                }
            } finally {
                rs.close()
            }
        } finally {
            getShiftStatement.close()
            conn.close()
        }

        return null
    }

    def saveShift(Shift shift) {
        Connection conn = getConnection()
        CallableStatement saveShiftStatement = conn.prepareCall("{ call saveShift(?, ?, ?) }")
        try {
            if (shift.id > 0) {
                saveShiftStatement.setInt(1, shift.id)
            } else {
                saveShiftStatement.setNull(1, Types.INTEGER)
            }
            saveShiftStatement.setString(2, gsonProvider.gson.toJson(shift, Shift.class))
            saveShiftStatement.executeUpdate()
            int shiftId = saveShiftStatement.getInt(3)
            shift.setId(shiftId) // Update the shift object with the new ID
            return shiftId
        } catch (Exception ex) {
            log.error(String.format("Error persisting shift for from retailer: %d store: %d tillId: %d error: %s", shift.getRetailerId(), shift.getStoreId(), shift.getTillId(), ex.getMessage()), ex)
            throw new RuntimeException(String.format("Error persisting shift for from retailer: %d store: %d tillId: %d error: %s", shift.getRetailerId(), shift.getStoreId(), shift.getTillId(), ex.getMessage()), ex)
        } finally{
            saveShiftStatement.close()
            conn.close()
        }
    }

    Shift createNewShift(int retailerId, int storeId, int tillId, boolean isAutoGenerated)  {
        try {
            return populateNewShift(retailerId, storeId, tillId, isAutoGenerated)
        } catch (Exception ex) {
            log.error(String.format("Error creating shift for retailer id: %s store id: %s till id: %s error: %s", retailerId, storeId, tillId, ex.getMessage()), ex)
            throw new RuntimeException(String.format("Error creating shift for retailer id: %s store id: %s till id: %s error: %s", retailerId, storeId, tillId, ex.getMessage()), ex)
        }
    }

    Shift getOpenShift(int retailerId, int storeId, int tillId) {
        Shift result = null;
        try (Connection conn = getConnection(); CallableStatement getShiftStatement = conn.prepareCall("{ call getShiftForTill(?, ?, ?) }")) {
            getShiftStatement.setInt(1, retailerId)
            getShiftStatement.setInt(2, storeId)
            getShiftStatement.setInt(3, tillId)

            try (ResultSet rs = getShiftStatement.executeQuery()) {
                if (rs.next()) {
                    String shiftJson = rs.getString("shift")
                    result = gsonProvider.gson.fromJson(shiftJson, Shift.class)
                }
            }
        } catch (SQLException ex) {
            log.error(String.format("Sql error loading shift for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, tillId, ex.getMessage()), ex)
            throw new RuntimeException(String.format("Sql error loading shift for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, tillId, ex.getMessage()), ex)
        } catch (Exception ex) {
            log.error(String.format("Unexpected error loading shift for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, tillId, ex.getMessage()), ex)
            throw new RuntimeException(String.format("Unexpected error loading shift for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, tillId, ex.getMessage()), ex)
        }
        return result
    }

    List<Shift> getShiftsForNonExistingTills(List<Shift> shiftList, Integer tillId){
        List<Shift> nonExistingShiftList = new ArrayList<>()
        Integer retailerId =  springSecurityService.principal.retailerId
        Integer storeId = springSecurityService.principal.storeId
        try {
            if (storeId != null) { //This action only runs on store level
                Store store = storeService.getStore(retailerId, storeId)
                Integer storeNumber = store.getConfig().getStoreNumber()
                List<TillConfiguration> tillConfigList = getAllActiveTills(storeNumber, tillId)
                Set<Integer> shiftTillIds = shiftList.stream().map(Shift::getTillId).collect(Collectors.toSet())

                Map<Integer, ShiftStatus> openTillsMap = shiftList.stream().filter(
                        shift -> shift.getShiftStatus() == ShiftStatus.OPEN)
                        .collect(Collectors.toMap(Shift::getTillId,
                                shift -> ShiftStatus.OPEN,
                                (existing, replacement) -> existing
                        ));

                nonExistingShiftList = tillConfigList.stream()
                        .filter(tillConfig -> !shiftTillIds.contains(tillConfig.getTillId()) || openTillsMap.get(tillConfig.getTillId()) == null)
                        .map(tillConfig -> {
                            Shift nonExistingShift = new Shift()
                            nonExistingShift.setId(0)
                            nonExistingShift.setRetailerId(tillConfig.getRetailerId())
                            nonExistingShift.setStoreId(storeId)
                            nonExistingShift.setTillId(tillConfig.getTillId())
                            return nonExistingShift
                        })
                        .collect(Collectors.toList())

            }
            return nonExistingShiftList
        } catch (Exception ex) {
            log.error(String.format("Error loading shift for non open tills from retailer: %d storeId: %s error: %s", retailerId, storeId, ex.getMessage()), ex)
            throw new RuntimeException(String.format("Unexpected error loading shift for non open tills from retailer: %d storeId: %s error: %s", retailerId, storeId, ex.getMessage()), ex)
        }
    }

    def validateParams(Map params) {
        def requiredFields = ['retailerId', 'storeId', 'tillId']
        requiredFields.each { field ->
            if (!params[field]) {
                throw new IllegalArgumentException("${field} cannot be null or empty")
            }
            if (!(params[field] ==~ /\d+/)) {
                throw new IllegalArgumentException("${field} must be a valid integer")
            }
        }
    }

    private Shift populateNewShift(int retailerId, int storeId, int tillId, boolean isAutoGenerated) throws Exception {
        int shiftNumber = getLastShiftNumber(retailerId, storeId, tillId) + 1
        FinancialWeek financialWeek = getFinancialWeek(retailerId)
        String userName = springSecurityService.principal.usersName
        User loggedInUser = userService.getUserByUsername(userName)
        Shift shift = new Shift(retailerId, storeId, tillId, -1, null)
        shift.setCustomerCount(0)
        shift.setShiftNumber(shiftNumber)
        shift.setCashInDrawer(BigDecimal.ZERO)
        shift.setShiftStatus(ShiftStatus.OPEN)
        shift.setShiftOpenTime(convertDateTimeToString(new DateTime()))
        shift.setShiftOpenUserId(loggedInUser.getId())
        shift.setShiftOpenUsername(loggedInUser.getUsername())
        if (financialWeek != null){
            shift.setFinancialWeek(financialWeek)
        }
        saveShift(shift) // Save shift
        addAudit(shift, ShiftAction.OPEN, isAutoGenerated, loggedInUser) // Audit for shift open action
        return shift;
    }

    private void addAudit(Shift shift, ShiftAction shiftAction, boolean isAutoGenerated, User loggedInUser){
        try {
            ShiftAudit shiftAudit = initializeShiftAudit(shift, shiftAction, isAutoGenerated, loggedInUser);
            saveShiftAudit(shiftAudit);
        } catch (Exception ex) {
            log.error("Error adding audit for shift id: " + shift.getId() + " : " + ex.getMessage(), ex);
        }
    }

    private ShiftAudit initializeShiftAudit(Shift shift, ShiftAction shiftAction, boolean isAutoGenerated, User loggedInUser) {
        ShiftAudit shiftAudit = new ShiftAudit();
        shiftAudit.setShiftId(shift.getId());
        shiftAudit.setAutoGenerated(isAutoGenerated);
        shiftAudit.setAction(shiftAction);
        shiftAudit.setUserId(loggedInUser?.id);
        shiftAudit.setUsername(loggedInUser?.username);
        shiftAudit.setTimestamp(new DateTime());
        return shiftAudit;
    }

    private List<TillConfiguration> getAllActiveTills(Integer storeNumber, Integer tillId) {
        return TillConfiguration.createCriteria().list {
            isNotNull('serialNumber')
            eq('retailerId', springSecurityService.principal.retailerId)
            if (storeNumber != null){ //In Till configuration table store id mean store number
                eq('storeId', storeNumber)
            }
            if (tillId != null) {
                eq('tillId', tillId)
            }
        } as List<TillConfiguration>
    }

    private Integer getLastShiftNumber(int retailerId, int storeId, int tillId) {
        int result = 0;
        try (Connection conn = getConnection(); CallableStatement getShiftNumberStmt = conn.prepareCall("{ call getPreviousShiftNumberForTill(?, ?, ?) }")) {
            getShiftNumberStmt.setInt(1, retailerId)
            getShiftNumberStmt.setInt(2, storeId)
            getShiftNumberStmt.setInt(3, tillId)

            try (ResultSet rs = getShiftNumberStmt.executeQuery()) {
                if (rs.next()) {
                    result = rs.getInt("shiftNumber")
                }
            }
        } catch (SQLException ex) {
            log.error(String.format("Sql error loading last shift number for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, tillId, ex.getMessage()), ex);
            throw new RuntimeException(String.format("Sql error loading last shift number for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, tillId, ex.getMessage()), ex);
        } catch (Exception ex) {
            log.error(String.format("Unexpected error loading last shift number for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, tillId, ex.getMessage()), ex);
            throw new RuntimeException(String.format("Unexpected error loading last shift number for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, tillId, ex.getMessage()), ex);
        }
        return result;
    }


    private FinancialWeek getFinancialWeek(int retailerId){
        FinancialWeek financialWeek =  null
        Date currentDate = convertToSqlDate(new DateTime())
        try (Connection conn = getConnection(); CallableStatement cstmt = conn.prepareCall("{ call getFinancialWeek(?, ?) }")) {
            cstmt.setInt(1, retailerId)
            cstmt.setDate(2, currentDate)
            try (ResultSet rs = cstmt.executeQuery()) {
                if (rs.next()) {
                    financialWeek = new FinancialWeek()
                    financialWeek.setId(rs.getInt("id"))
                    financialWeek.setRetailerId(rs.getInt("retailerId"))
                    financialWeek.setStartDate(rs.getDate("startDate"))
                    financialWeek.setFinancialYear(rs.getString("financialYear"))
                    financialWeek.setWeekNumber(rs.getInt("weekNumber"))
                }
            }
        } catch (SQLException ex) {
            log.error(String.format("Sql error loading financial week from retailer: %d date: %s error: %s", retailerId, currentDate, ex.getMessage()), ex)
        } catch (Exception ex) {
            log.error(String.format("Unexpected error loading financial week from retailer: %d date: %s error: %s", retailerId, currentDate, ex.getMessage()), ex)
        }
        return financialWeek;
    }

    private void saveShiftAudit(ShiftAudit shiftAudit){
        try (Connection conn = getConnection(); CallableStatement saveShiftStatement = conn.prepareCall("{ call saveShiftAudit(?, ?, ?, ?, ?, ?, ?, ?) }")) {
            if (shiftAudit.getId() > 0) {
                saveShiftStatement.setInt(1, shiftAudit.getId())
            } else {
                saveShiftStatement.setNull(1, Types.INTEGER)
            }
            saveShiftStatement.setInt(2, shiftAudit.getShiftId())
            saveShiftStatement.setBoolean(3, shiftAudit.isAutoGenerated())
            saveShiftStatement.setString(4, shiftAudit.getAction().toString())
            saveShiftStatement.setInt(5, shiftAudit.getUserId())
            saveShiftStatement.setString(6, shiftAudit.getUsername())
            saveShiftStatement.setTimestamp(7, convertToSqlTimestamp(shiftAudit.getTimestamp()))
            saveShiftStatement.setObject(8, shiftAudit.getExtras())
            saveShiftStatement.executeUpdate();
        } catch (SQLException ex) {
            log.error(String.format("Sql error saving shift audit for shift id: %s error: %s", shiftAudit.getShiftId(), ex.getMessage()), ex)
            throw new RuntimeException(String.format("Sql error saving shift audit for shift id: %s error: %s", shiftAudit.getShiftId(), ex.getMessage()), ex)
        } catch (Exception ex) {
            log.error(String.format("Unexpected error saving shift audit for shift id: %s error: %s", shiftAudit.getShiftId(), ex.getMessage()), ex)
            throw new RuntimeException(String.format("Unexpected error saving shift audit for shift id: %s error: %s", shiftAudit.getShiftId(), ex.getMessage()), ex)
        }
    }

    private  Date convertToSqlDate(DateTime date) {
        return new Date(date.withTimeAtStartOfDay().getMillis());
    }

    private String convertDateTimeToString(DateTime dateTime) {
        if(dateTime == null) {
            return null;
        }
        DateTimeFormatter formatter = DateTimeFormat.forPattern(DATE_PATTERN_YYYYMMDD_HHMMSS);
        return dateTime.toString(formatter);
    }

    private Timestamp convertToSqlTimestamp(DateTime dateTime) {
        if (dateTime != null){
            return new Timestamp(dateTime.getMillis());
        }
        return new Timestamp(new DateTime().getMillis());
    }

}