package uk.co.wonderlane.wlpos

import grails.gorm.transactions.Transactional
import org.joda.time.DateTime
import org.joda.time.format.DateTimeFormat
import org.joda.time.format.DateTimeFormatter
import uk.co.wonderlane.wlpos.dataaccess.DatabaseCredentials
import uk.co.wonderlane.wlpos.dataaccess.MySqlPoolDal
import uk.co.wonderlane.wlpos.entities.cash.ReconciliationTotal
import uk.co.wonderlane.wlpos.entities.cash.Shift
import uk.co.wonderlane.wlpos.entities.cash.Snapshot
import uk.co.wonderlane.wlpos.entities.cash.TenderTotal
import uk.co.wonderlane.wlpos.entities.cashmanagement.CashManagementConfig
import uk.co.wonderlane.wlpos.entities.transaction.FinancialWeek
import uk.co.wonderlane.wlpos.entities.transaction.ShiftAudit
import uk.co.wonderlane.wlpos.enums.*
import uk.co.wonderlane.wlpos.reporting.Location

import java.sql.*
import java.util.stream.Collectors

@Transactional
class ShiftService extends MySqlPoolDal {

    def springSecurityService
    def gsonProvider
    def storeService
    def userService
    def cashManagementService
    def snapshotService
    def locationService
    def reportingService

    public static String DATE_PATTERN_YYYYMMDD_HHMMSS = "yyyy-MM-dd HH:mm:ss";

    ShiftService(DatabaseCredentials databaseCredentials) {
        super(databaseCredentials)
    }

    Shift createNewShift(int retailerId, int storeId, int tillId, boolean isAutoGenerated)  {
        try {
            return populateNewShift(retailerId, storeId, tillId, isAutoGenerated)
        } catch (Exception ex) {
            log.error(String.format("Error creating shift for retailer id: %s store id: %s till id: %s error: %s", retailerId, storeId, tillId, ex.getMessage()), ex)
            throw new RuntimeException(String.format("Error creating shift for retailer id: %s store id: %s till id: %s error: %s", retailerId, storeId, tillId, ex.getMessage()), ex)
        }
    }

    void processShiftClose(Shift shift){
        try {
            User loggedInUser = loadLoggedInUser()
            populateShiftCloseFields(shift, loggedInUser) //Update status of current shift if
            saveShift(shift) //This will called shift save method to process close
            addAudit(shift, ShiftAction.CLOSE, false, loggedInUser) //Add shift audit for shift close
        } catch (Exception ex) {
            log.error(String.format("Error closing shift for retailer id: %s store id: %s till id: %s error: %s", shift.getRetailerId(), shift.getStoreId(), shift.getTillId(), ex.getMessage()), ex)
            throw new RuntimeException(String.format("Error creating shift for retailer id: %s store id: %s till id: %s error: %s", shift.getRetailerId(), shift.getStoreId(), shift.getTillId(), ex.getMessage()), ex)
        }
    }

    void processShiftCashSave(CashUpCommand cashUpCommand, Shift shift){
        try {
            updateOnHoldCashTotal(cashUpCommand, shift) //This will update onhold cash attribute on shift object for temporary
            updateOnHoldVoucherTotal(cashUpCommand, shift) //This will update onhold voucher attribute on shift object for temporary
            saveShift(shift) //This will called shift save method to process on hold cash and voucher values
        } catch (Exception ex) {
            log.error(String.format("Error closing shift for retailer id: %s store id: %s till id: %s error: %s", shift.getRetailerId(), shift.getStoreId(), shift.getTillId(), ex.getMessage()), ex)
            throw new RuntimeException(String.format("Error creating shift for retailer id: %s store id: %s till id: %s error: %s", shift.getRetailerId(), shift.getStoreId(), shift.getTillId(), ex.getMessage()), ex)
        }
    }

    def getSafeLocation(Shift shift){
        def safeLocations = null
        try {
            safeLocations = locationService.getStoreSafeLocations()
            if (safeLocations.collect().isEmpty()) {
                Location location = new Location()
                location.safeId = 1
                location.retailerId = shift.retailerId
                location.storeId = shift.storeId
                location.type = LocationType.SAFE
                location.description = "Safe 1"
                location.save()
                safeLocations = locationService.getStoreSafeLocations()
            }
        } catch (Exception ex) {
            log.error(String.format("Error saving safe location shift for retailer id: %s store id: %s till id: %s error: %s", shift.getRetailerId(), shift.getStoreId(), shift.getTillId(), ex.getMessage()), ex)
        }
        return safeLocations
    }

    void processShiftDataSave(SaveShiftCommand saveShiftCommand, Shift shift){
        try {
            User loggedInUser = loadLoggedInUser()
            // This method will populate shift data corresponding at action requested
            // Based on request (reconcile, recount or finalise) shift object is populated differently
            updateShiftSaveFields(saveShiftCommand, shift, loggedInUser)
            saveShift(shift) //This will called shift save method to process close
            ShiftAction auditShiftAction = saveShiftCommand.isFinalise ? ShiftAction.FINALISE : saveShiftCommand.isRecount ? ShiftAction.RECOUNT : ShiftAction.RECONCILE
            addAudit(shift, auditShiftAction, false, loggedInUser) //Add shift audit for shift close
        } catch (Exception ex) {
            log.error(String.format("Error processing shift summary for retailer id: %s store id: %s till id: %s error: %s", shift.getRetailerId(), shift.getStoreId(), shift.getTillId(), ex.getMessage()), ex)
            throw new RuntimeException(String.format("Error processing shift summary for retailer id: %s store id: %s till id: %s error: %s", shift.getRetailerId(), shift.getStoreId(), shift.getTillId(), ex.getMessage()), ex)
        }
    }


    void processTakeSnapshot(Shift shift, SaveShiftCommand saveShiftCommand) {
        try {
            Snapshot latestSnapshot = snapshotService.getSnapshotForLocation(saveShiftCommand.safeLocationId)
            processSnapshotCalculation(latestSnapshot, shift, TenderType.CASH)
            processSnapshotCalculation(latestSnapshot, shift, TenderType.VOUCHER)
            snapshotService.saveSnapshot(latestSnapshot)
        }catch (Exception ex){
            log.error(String.format("Error taking shift snapshot for retailer id: %s store id: %s till id: %s error: %s", shift.getRetailerId(), shift.getStoreId(), shift.getTillId(), ex.getMessage()), ex)
        }
    }

    void updateTenderMovement(Shift shift, SaveShiftCommand saveShiftCommand){
        try {
            def tillLocation = locationService.getTillLocation(shift.tillId)
            def safeLocation = locationService.getLocation(saveShiftCommand.safeLocationId)

            shift.reconciliationTotals.each {
                if (it.value > BigDecimal.ZERO) {
                    reportingService.saveTenderMovement(reportingService.createNewTenderMovement(TenderMovementType.CASH_UP,
                            it.tenderType,
                            tillLocation as uk.co.wonderlane.wlpos.reporting.Location,
                            safeLocation as uk.co.wonderlane.wlpos.reporting.Location,
                            it.value))
                }
            }
        } catch (Exception ex) {
            log.error(String.format("Error shift tender movement for retailer id: %s store id: %s till id: %s error: %s", shift.getRetailerId(), shift.getStoreId(), shift.getTillId(), ex.getMessage()), ex)
        }

    }

    boolean isShiftRecountAmountNotExceed(Shift shift){
        try {
            int configuredRecountAttempts = getConfiguredRecountAttempts(shift.getRetailerId(), shift.getStoreId())
            if(shift.getShiftStatus() == ShiftStatus.RECONCILED) {
                int currentTotalRecountAttempts = shift.getTotalRecountAttempts() != null ? shift.getTotalRecountAttempts() : 0
                if (configuredRecountAttempts > 0 && currentTotalRecountAttempts < configuredRecountAttempts) {
                    return true
                }
            }
            return false
        } catch (Exception ex) {
            log.error(String.format("Error checking recount amount for retailer id: %s store id: %s till id: %s error: %s", shift.getRetailerId(), shift.getStoreId(), shift.getTillId(), ex.getMessage()), ex)
            throw new RuntimeException(String.format("Error checking recount amount for retailer id: %s store id: %s till id: %s error: %s", shift.getRetailerId(), shift.getStoreId(), shift.getTillId(), ex.getMessage()), ex)
        }

    }

    int getConfiguredRecountAttempts(int retailerId, int storeId){
        try {
            CashManagementConfig cashManagementConfig = cashManagementService.getCashManagementConfig(retailerId, storeId)
            if (cashManagementConfig != null) {
                return cashManagementConfig.getTillShiftRecountLimit()
            }
            return -1
        } catch (Exception ex) {
            log.error(String.format("Error loading cash management configuration for retailer id: %s store id: %s error: %s", retailerId, storeId, ex.getMessage()), ex)
            throw new RuntimeException(String.format("Error loading cash management configuration for retailer id: %s store id: %s error: %s", retailerId, storeId, ex.getMessage()), ex)
        }
    }

    boolean postTillControlEventProcess(Shift shift) {
        boolean isNewShiftOpen = false
        try {
            if (!ShiftStatus.OPEN.equals(shift.getShiftStatus())) {
                if (isTillShiftsAutoOpen(shift.getRetailerId(), shift.getStoreId())) {
                    createNewShift(shift.getRetailerId(), shift.getStoreId(), shift.getTillId(), true)
                    isNewShiftOpen = true
                }
            }
        } catch (Exception ex) {
            log.error(String.format("Error in post shift close event process for shift id: %d retailer id: %s store id: %s till id: %s error: %s", shift.getId(), shift.getRetailerId(), shift.getStoreId(), shift.getTillId(), ex.getMessage()), ex)
        }
        return isNewShiftOpen
    }

    def getShifts(Integer tillId) {
        List<Shift> shifts = new ArrayList<>()
        Connection conn = getConnection()
        CallableStatement getShiftsStatement = conn.prepareCall("{ call getActiveShifts(?, ?, ?) }")
        try {
            getShiftsStatement.setInt(1, springSecurityService.principal.retailerId)
            if (springSecurityService.principal.storeId != null) {
                getShiftsStatement.setInt(2, springSecurityService.principal.storeId)
            } else {
                getShiftsStatement.setNull(2, Types.INTEGER)
            }
            if (tillId != null) {
                getShiftsStatement.setInt(3, tillId)
            } else {
                getShiftsStatement.setNull(3, Types.INTEGER)
            }
            ResultSet rs = getShiftsStatement.executeQuery()
            try {
                while (rs.next()) {
                    String shiftJson = rs.getString("shift")

                    shifts.add(gsonProvider.gson.fromJson(shiftJson, Shift.class))
                }
            } finally {
                rs.close()
            }
        }catch (Exception ex) {
            log.error(String.format("Error loading active shift for retailer: %d shiftId: %d error: %s", springSecurityService.principal.retailerId, tillId, ex.getMessage()), ex)
            throw new RuntimeException(String.format("Error loading active shift for retailer: %d tillId: %d error: %s", springSecurityService.principal.retailerId, tillId, ex.getMessage()), ex)
        } finally {
            getShiftsStatement.close()
            conn.close();
        }

        return shifts
    }

    def getShift(int shiftId, int retailerId, int storeId) {
        Connection conn = getConnection()
        CallableStatement getShiftStatement = conn.prepareCall("{ call getShift(?, ?, ?) }")
        try {
            getShiftStatement.setInt(1, retailerId > 0 ? retailerId : springSecurityService.principal.retailerId)
            getShiftStatement.setInt(2, storeId > 0 ? storeId : springSecurityService.principal.storeId)
            getShiftStatement.setInt(3, shiftId)
            ResultSet rs = getShiftStatement.executeQuery()
            try {
                if (rs.next()) {
                    String shiftJson = rs.getString("shift")
                    return gsonProvider.gson.fromJson(shiftJson, Shift.class)
                }
            } finally {
                rs.close()
            }
        }catch (Exception ex) {
            log.error(String.format("Error loading shift for from retailer: %d store: %d shiftId: %d error: %s", retailerId, storeId, shiftId, ex.getMessage()), ex)
            throw new RuntimeException(String.format("Error persisting shift for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, shiftId, ex.getMessage()), ex)
        } finally {
            getShiftStatement.close()
            conn.close()
        }

        return null
    }

    def saveShift(Shift shift) {
        Connection conn = getConnection()
        CallableStatement saveShiftStatement = conn.prepareCall("{ call saveShift(?, ?, ?) }")
        try {
            if (shift.id > 0) {
                saveShiftStatement.setInt(1, shift.id)
            } else {
                saveShiftStatement.setNull(1, Types.INTEGER)
            }
            saveShiftStatement.setString(2, gsonProvider.gson.toJson(shift, Shift.class))
            saveShiftStatement.executeUpdate()
            int shiftId = saveShiftStatement.getInt(3)
            shift.setId(shiftId) // Update the shift object with the new ID
            return shiftId
        } catch (Exception ex) {
            log.error(String.format("Error persisting shift for from retailer: %d store: %d tillId: %d error: %s", shift.getRetailerId(), shift.getStoreId(), shift.getTillId(), ex.getMessage()), ex)
            throw new RuntimeException(String.format("Error persisting shift for from retailer: %d store: %d tillId: %d error: %s", shift.getRetailerId(), shift.getStoreId(), shift.getTillId(), ex.getMessage()), ex)
        } finally{
            saveShiftStatement.close()
            conn.close()
        }
    }

    Shift getOpenShift(int retailerId, int storeId, int tillId) {
        Shift result = null;
        try (Connection conn = getConnection(); CallableStatement getShiftStatement = conn.prepareCall("{ call getShiftForTill(?, ?, ?) }")) {
            getShiftStatement.setInt(1, retailerId)
            getShiftStatement.setInt(2, storeId)
            getShiftStatement.setInt(3, tillId)

            try (ResultSet rs = getShiftStatement.executeQuery()) {
                if (rs.next()) {
                    String shiftJson = rs.getString("shift")
                    result = gsonProvider.gson.fromJson(shiftJson, Shift.class)
                }
            }
        } catch (SQLException ex) {
            log.error(String.format("Sql error loading shift for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, tillId, ex.getMessage()), ex)
            throw new RuntimeException(String.format("Sql error loading shift for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, tillId, ex.getMessage()), ex)
        } catch (Exception ex) {
            log.error(String.format("Unexpected error loading shift for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, tillId, ex.getMessage()), ex)
            throw new RuntimeException(String.format("Unexpected error loading shift for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, tillId, ex.getMessage()), ex)
        }
        return result
    }

    List<Shift> getShiftsForNonExistingTills(List<Shift> shiftList, Integer tillId){
        List<Shift> nonExistingShiftList = new ArrayList<>()
        Integer retailerId =  springSecurityService.principal.retailerId
        Integer storeId = springSecurityService.principal.storeId
        try {
            if (storeId != null) { //This action only runs on store level
                Store store = storeService.getStore(retailerId, storeId)
                Integer storeNumber = store.getConfig().getStoreNumber()
                List<TillConfiguration> tillConfigList = getAllActiveTills(storeNumber, tillId)
                Set<Integer> shiftTillIds = shiftList.stream().map(Shift::getTillId).collect(Collectors.toSet())

                Map<Integer, ShiftStatus> openTillsMap = shiftList.stream().filter(
                        shift -> shift.getShiftStatus() == ShiftStatus.OPEN)
                        .collect(Collectors.toMap(Shift::getTillId,
                                shift -> ShiftStatus.OPEN,
                                (existing, replacement) -> existing
                        ));

                nonExistingShiftList = tillConfigList.stream()
                        .filter(tillConfig -> !shiftTillIds.contains(tillConfig.getTillId()) || openTillsMap.get(tillConfig.getTillId()) == null)
                        .map(tillConfig -> {
                            Shift nonExistingShift = new Shift()
                            nonExistingShift.setId(0)
                            nonExistingShift.setRetailerId(tillConfig.getRetailerId())
                            nonExistingShift.setStoreId(storeId)
                            nonExistingShift.setTillId(tillConfig.getTillId())
                            return nonExistingShift
                        })
                        .collect(Collectors.toList())

            }
            return nonExistingShiftList
        } catch (Exception ex) {
            log.error(String.format("Error loading shift for non open tills from retailer: %d storeId: %s error: %s", retailerId, storeId, ex.getMessage()), ex)
            throw new RuntimeException(String.format("Unexpected error loading shift for non open tills from retailer: %d storeId: %s error: %s", retailerId, storeId, ex.getMessage()), ex)
        }
    }

    def validateParams(Map params) {
        def requiredFields = ['retailerId', 'storeId', 'tillId']
        requiredFields.each { field ->
            if (!params[field]) {
                throw new IllegalArgumentException("${field} cannot be null or empty")
            }
            if (!(params[field] ==~ /\d+/)) {
                throw new IllegalArgumentException("${field} must be a valid integer")
            }
        }
    }

    private Shift populateNewShift(int retailerId, int storeId, int tillId, boolean isAutoGenerated) throws Exception {
        int shiftNumber = getLastShiftNumber(retailerId, storeId, tillId) + 1
        FinancialWeek financialWeek = getFinancialWeek(retailerId)
        User loggedInUser = loadLoggedInUser()
        Shift shift = new Shift(retailerId, storeId, tillId, -1, null)
        shift.setCustomerCount(0)
        shift.setShiftNumber(shiftNumber)
        shift.setCashInDrawer(BigDecimal.ZERO)
        shift.setShiftStatus(ShiftStatus.OPEN)
        shift.setShiftOpenTime(convertDateTimeToString(new DateTime()))
        shift.setShiftOpenUserId(loggedInUser.getId())
        shift.setShiftOpenUsername(loggedInUser.getUsername())
        if (financialWeek != null){
            shift.setFinancialWeek(financialWeek)
        }
        saveShift(shift) // Save shift
        addAudit(shift, ShiftAction.OPEN, isAutoGenerated, loggedInUser) // Audit for shift open action
        return shift;
    }

    private void addAudit(Shift shift, ShiftAction shiftAction, boolean isAutoGenerated, User loggedInUser){
        try {
            ShiftAudit shiftAudit = initializeShiftAudit(shift, shiftAction, isAutoGenerated, loggedInUser)
            saveShiftAudit(shiftAudit)
        } catch (Exception ex) {
            log.error("Error adding audit for shift id: " + shift.getId() + " : " + ex.getMessage(), ex);
        }
    }

    private ShiftAudit initializeShiftAudit(Shift shift, ShiftAction shiftAction, boolean isAutoGenerated, User loggedInUser) {
        ShiftAudit shiftAudit = new ShiftAudit()
        shiftAudit.setShiftId(shift.getId())
        shiftAudit.setAutoGenerated(isAutoGenerated)
        shiftAudit.setAction(shiftAction)
        shiftAudit.setUserId(loggedInUser?.id)
        shiftAudit.setUsername(loggedInUser?.username)
        shiftAudit.setTimestamp(new DateTime())
        return shiftAudit
    }

    private List<TillConfiguration> getAllActiveTills(Integer storeNumber, Integer tillId) {
        return TillConfiguration.createCriteria().list {
            and {
                isNotNull('serialNumber')
                ne('serialNumber', '')  // Exclude empty strings
            }
            eq('retailerId', springSecurityService.principal.retailerId)
            if (storeNumber != null){ //In Till configuration table store id mean store number
                eq('storeId', storeNumber)
            }
            if (tillId != null) {
                eq('tillId', tillId)
            }
        } as List<TillConfiguration>
    }

    private Integer getLastShiftNumber(int retailerId, int storeId, int tillId) {
        int result = 0;
        try (Connection conn = getConnection(); CallableStatement getShiftNumberStmt = conn.prepareCall("{ call getPreviousShiftNumberForTill(?, ?, ?) }")) {
            getShiftNumberStmt.setInt(1, retailerId)
            getShiftNumberStmt.setInt(2, storeId)
            getShiftNumberStmt.setInt(3, tillId)

            try (ResultSet rs = getShiftNumberStmt.executeQuery()) {
                if (rs.next()) {
                    result = rs.getInt("shiftNumber")
                }
            }
        } catch (SQLException ex) {
            log.error(String.format("Sql error loading last shift number for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, tillId, ex.getMessage()), ex);
            throw new RuntimeException(String.format("Sql error loading last shift number for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, tillId, ex.getMessage()), ex);
        } catch (Exception ex) {
            log.error(String.format("Unexpected error loading last shift number for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, tillId, ex.getMessage()), ex);
            throw new RuntimeException(String.format("Unexpected error loading last shift number for from retailer: %d store: %d tillId: %d error: %s", retailerId, storeId, tillId, ex.getMessage()), ex);
        }
        return result;
    }


    private FinancialWeek getFinancialWeek(int retailerId){
        FinancialWeek financialWeek =  null
        Date currentDate = convertToSqlDate(new DateTime())
        try (Connection conn = getConnection(); CallableStatement cstmt = conn.prepareCall("{ call getFinancialWeek(?, ?) }")) {
            cstmt.setInt(1, retailerId)
            cstmt.setDate(2, currentDate)
            try (ResultSet rs = cstmt.executeQuery()) {
                if (rs.next()) {
                    financialWeek = new FinancialWeek()
                    financialWeek.setId(rs.getInt("id"))
                    financialWeek.setRetailerId(rs.getInt("retailerId"))
                    financialWeek.setStartDate(rs.getDate("startDate"))
                    financialWeek.setFinancialYear(rs.getString("financialYear"))
                    financialWeek.setWeekNumber(rs.getInt("weekNumber"))
                }
            }
        } catch (SQLException ex) {
            log.error(String.format("Sql error loading financial week from retailer: %d date: %s error: %s", retailerId, currentDate, ex.getMessage()), ex)
        } catch (Exception ex) {
            log.error(String.format("Unexpected error loading financial week from retailer: %d date: %s error: %s", retailerId, currentDate, ex.getMessage()), ex)
        }
        return financialWeek
    }

    private void saveShiftAudit(ShiftAudit shiftAudit){
        try (Connection conn = getConnection(); CallableStatement saveShiftStatement = conn.prepareCall("{ call saveShiftAudit(?, ?, ?, ?, ?, ?, ?, ?) }")) {
            if (shiftAudit.getId() > 0) {
                saveShiftStatement.setInt(1, shiftAudit.getId())
            } else {
                saveShiftStatement.setNull(1, Types.INTEGER)
            }
            saveShiftStatement.setInt(2, shiftAudit.getShiftId())
            saveShiftStatement.setBoolean(3, shiftAudit.isAutoGenerated())
            saveShiftStatement.setString(4, shiftAudit.getAction().toString())
            saveShiftStatement.setInt(5, shiftAudit.getUserId())
            saveShiftStatement.setString(6, shiftAudit.getUsername())
            saveShiftStatement.setTimestamp(7, convertToSqlTimestamp(shiftAudit.getTimestamp()))
            saveShiftStatement.setObject(8, shiftAudit.getExtras())
            saveShiftStatement.executeUpdate();
        } catch (SQLException ex) {
            log.error(String.format("Sql error saving shift audit for shift id: %s error: %s", shiftAudit.getShiftId(), ex.getMessage()), ex)
            throw new RuntimeException(String.format("Sql error saving shift audit for shift id: %s error: %s", shiftAudit.getShiftId(), ex.getMessage()), ex)
        } catch (Exception ex) {
            log.error(String.format("Unexpected error saving shift audit for shift id: %s error: %s", shiftAudit.getShiftId(), ex.getMessage()), ex)
            throw new RuntimeException(String.format("Unexpected error saving shift audit for shift id: %s error: %s", shiftAudit.getShiftId(), ex.getMessage()), ex)
        }
    }

    private  Date convertToSqlDate(DateTime date) {
        return new Date(date.withTimeAtStartOfDay().getMillis());
    }

    private String convertDateTimeToString(DateTime dateTime) {
        if(dateTime == null) {
            return null;
        }
        DateTimeFormatter formatter = DateTimeFormat.forPattern(DATE_PATTERN_YYYYMMDD_HHMMSS);
        return dateTime.toString(formatter);
    }

    private Timestamp convertToSqlTimestamp(DateTime dateTime) {
        if (dateTime != null){
            return new Timestamp(dateTime.getMillis());
        }
        return new Timestamp(new DateTime().getMillis());
    }

    private void populateShiftCloseFields(Shift shift, User loggedUser) {
        shift.setShiftStatus(ShiftStatus.UNRECONCILED);
        shift.setShiftCloseTime(convertDateTimeToString(new DateTime()))
        shift.setShiftCloseUserId(loggedUser.getId())
        shift.setShiftCloseUsername(loggedUser.getUsername())
    }

    private User loadLoggedInUser(){
        int id = springSecurityService.principal.id
        User loggedInUser = userService.getUser(id)
        return loggedInUser
    }

    private void processSnapshotCalculation(Snapshot snapshot, Shift shift, TenderType type) {
        def total = shift.reconciliationTotals.find { it.tenderType == type }
        if (total) {
            def expected = snapshot.expectedTotals.find { it.tenderType == type }
            if (!expected) {
                expected = new TenderTotal(type)
                snapshot.expectedTotals.add(expected)
            }
            expected.value = expected.value.add(total.value)
        }
    }

    private void updateCashTotal(Shift shift) {
        //Load on hold cash total values --> Saved at cash up view
        def cashOnHoldTotal = shift.onHoldReconciliationTotals.find { it.tenderType == TenderType.CASH }

        //Then update onhold cash value to shift actual cash value
        def cashTotal = shift.reconciliationTotals.find { it.tenderType == TenderType.CASH } ?:
                new ReconciliationTotal(TenderType.CASH).tap { shift.reconciliationTotals << it }
        cashTotal.value = cashOnHoldTotal?.value ?: BigDecimal.ZERO
        cashTotal.variance = cashOnHoldTotal?.variance ?: BigDecimal.ZERO
    }

    private void updateVoucherTotal(Shift shift) {
        //Load on hold voucher total values --> Saved at cash up view
        def vouchersOnHoldTotal = shift.onHoldReconciliationTotals.find { it.tenderType == TenderType.VOUCHER }

        //Then update onhold voucher value to shift actual voucher value
        def vouchersTotal = shift.reconciliationTotals.find { it.tenderType == TenderType.VOUCHER } ?:
                new ReconciliationTotal(TenderType.VOUCHER).tap { shift.reconciliationTotals << it }
        vouchersTotal.value = vouchersOnHoldTotal?.value ?: BigDecimal.ZERO
        vouchersTotal.variance = vouchersOnHoldTotal?.variance ?: BigDecimal.ZERO
    }

    private void updateOnHoldCashTotal(CashUpCommand cashUpCommand, Shift shift) {
        def cashTotal = shift.onHoldReconciliationTotals.find { it.tenderType == TenderType.CASH } ?:
                new ReconciliationTotal(TenderType.CASH).tap { shift.onHoldReconciliationTotals << it }
        cashTotal.value = calculateCashTotal(cashUpCommand)
        cashTotal.variance = (cashTotal.value ?: 0) - (shift.cashInDrawer ?: 0)
    }

    private void updateOnHoldVoucherTotal(CashUpCommand cashUpCommand, Shift shift) {
        def vouchersTotal = shift.onHoldReconciliationTotals.find { it.tenderType == TenderType.VOUCHER } ?:
                new ReconciliationTotal(TenderType.VOUCHER).tap { shift.onHoldReconciliationTotals << it }
        vouchersTotal.value = cashUpCommand.vouchersTotal
        vouchersTotal.variance = (vouchersTotal.value ?: 0) - (shift.tenderTotals.findAll { it.tenderType == TenderType.VOUCHER }*.value.sum() ?: 0)
    }

    private BigDecimal calculateCashTotal(CashUpCommand cashUpCommand) {
        switch(cashUpCommand.cashUpBy) {
            case "VALUE":
                return sumDenominations(cashUpCommand)
            case "DENOMINATION":
                return sumDenominationsWithMultipliers(cashUpCommand)
            default:
                return cashUpCommand.cashTotal
        }
    }

    private BigDecimal sumDenominations(CashUpCommand cmd) {
        ([cmd.fiftyPounds, cmd.twentyPounds, cmd.tenPounds, cmd.fivePounds, cmd.twoPounds, cmd.onePounds, cmd.fiftyPences, cmd.twentyPences, cmd.tenPences,
          cmd.fivePences, cmd.twoPences, cmd.onePences].sum() ?: 0) as BigDecimal
    }

    private BigDecimal sumDenominationsWithMultipliers(CashUpCommand cmd) {
        ([cmd.fiftyPounds * 50, cmd.twentyPounds * 20, cmd.tenPounds * 10, cmd.fivePounds * 5, cmd.twoPounds * 2, cmd.onePounds, cmd.fiftyPences * 0.50, cmd.twentyPences * 0.20,
          cmd.tenPences * 0.10, cmd.fivePences * 0.05, cmd.twoPences * 0.02, cmd.onePences * 0.01].sum() ?: 0) as BigDecimal
    }

    private void updateShiftSaveFields(SaveShiftCommand saveShiftCommand, Shift shift, User loggedInUser){
        if (shift.shiftStatus == ShiftStatus.UNRECONCILED || shift.shiftStatus == ShiftStatus.RECONCILED){
            if (!saveShiftCommand.isFinalise){
                // If the request is not a final request (Intermediate --> reconcile or recount)
                // Then should
                //   1. Move on hold cash values into shift cash value
                //   2. Move on hold voucher values into shift voucher value
                //   3. Update variance reason and reason text
                //   4. Safe location to move
                updateCashTotal(shift) // Update on hold cash into actual shift object cash
                updateVoucherTotal(shift) // Update on hold voucher into actual shift object voucher
                if (saveShiftCommand.tenderReconciliationVarianceReason != null) { // Update variance and variance text
                    shift.reconciliationTotals.findAll { it.variance != BigDecimal.ZERO }?.each {
                        it.varianceReason = saveShiftCommand.tenderReconciliationVarianceReason
                        it.varianceReasonText = saveShiftCommand.tenderReconciliationVarianceReasonText
                    }
                }
                if (!saveShiftCommand.isRecount){
                    shift.reconciledDate = DateTime.now()
                    shift.reconciledByUserId = loggedInUser.getId()
                    shift.reconciledByUsersName = loggedInUser.getUsername()
                    shift.shiftStatus = ShiftStatus.RECONCILED
                } else {
                    shift.reReconciledDate = DateTime.now()
                    shift.reReconciledByUserId = loggedInUser.getId()
                    shift.reReconciledByUsersName = loggedInUser.getUsername()
                    shift.totalRecountAttempts = (shift.totalRecountAttempts ?: 0) + 1
                }
                // Once update done clear `onhold` list
                shift.getOnHoldReconciliationTotals().clear()
            } else {
                shift.shiftStatus = ShiftStatus.FINALISED
            }
        }
    }

    private boolean isTillShiftsAutoOpen(int retailerId, int storeId) {
        try {
            CashManagementConfig cashManagementConfig = cashManagementService.getCashManagementConfig(retailerId, storeId)
            if (cashManagementConfig != null && !cashManagementConfig.isTillShiftsManualOpen()) {
                return true
            }
            return false
        } catch (Exception ex) {
            log.error(String.format("Error checking shift auto open for retailer id: %s store id: %s error: %s", retailerId, storeId, ex.getMessage()), ex)
            throw new RuntimeException(String.format("Error checking recount amount for retailer id: %s store id: %s error: %s", retailerId, storeId, ex.getMessage()), ex)
        }
    }

}