package uk.co.wonderlane.wlpos

import grails.gorm.transactions.Transactional
import uk.co.wonderlane.wlpos.entities.cash.SafeSession
import uk.co.wonderlane.wlpos.entities.cash.Shift
import uk.co.wonderlane.wlpos.entities.cash.TenderTotal
import uk.co.wonderlane.wlpos.enums.SafeSessionAction
import uk.co.wonderlane.wlpos.enums.ShiftAction
import uk.co.wonderlane.wlpos.enums.ShiftStatus
import uk.co.wonderlane.wlpos.enums.TenderMovementType
import uk.co.wonderlane.wlpos.enums.TenderType

import java.util.stream.Collectors

@Transactional
class TenderMovementService {

    def springSecurityService
    def storeService
    def reportingService
    def locationService
    def safeManagementService
    def shiftService
    def userService
    def safeService

    List<TillConfiguration> getAllActiveTills() {
        Integer retailerId =  springSecurityService.principal.retailerId
        Integer storeId = springSecurityService.principal.storeId
        Store store = storeService.getStore(retailerId, storeId)
        Integer storeNumber = store.getConfig().getStoreNumber()
        return TillConfiguration.createCriteria().list {
            and {
                isNotNull('serialNumber')
                ne('serialNumber', '')  // Exclude empty strings
                eq('cashManagementEnabled', true)  // Only return entries with cashManagementEnabled = true
            }
            eq('retailerId', springSecurityService.principal.retailerId)
            if (storeNumber != null) { //In Till configuration table store id means store number
                eq('storeId', storeNumber)
            }

            // Sort by tillId in ascending order
            order('tillId', 'asc')

        } as List<TillConfiguration>
    }

    //Return eligible tenders for tender lift (Here it is only CASH and VOUCHER)
    List<TenderType> getEligibleTendersForTenderLift() {
        return Arrays.stream(TenderType.values()).filter(type -> type == TenderType.CASH || type == TenderType.VOUCHER)
                .collect(Collectors.toList());
    }

    List<TenderType> getCashOnlyTenders() {
        return Arrays.stream(TenderType.values()).filter(type -> type == TenderType.CASH)
                .collect(Collectors.toList());
    }

    //Update shift values and add a audit for tender lift
    void updateShiftBalanceTotals(ShiftAction shiftAction, TenderType tenderType, BigDecimal updateAmount, Integer tenderMovementId, int tillId){
        Shift shift = shiftService.getOpenShift(springSecurityService.principal.retailerId, springSecurityService.principal.storeId, tillId)
        User loggedInUser = loadLoggedInUser()
        updateShiftBalance(shift, tenderType, updateAmount)
        addShiftAudit(shift, shiftAction, true,  loggedInUser, tenderMovementId)
    }

    //Update safe session values and add a audit for tender lift
    void updateSafeSessionBalanceTotals(SafeSessionAction safeSessionAction, TenderType tenderType, BigDecimal updateAmount, Integer tenderMovementId, int safeId){
        User loggedInUser = loadLoggedInUser()
        SafeSession safeSession =  safeSessionUpdate(safeId, tenderType, updateAmount) //Update safe session
        addSafeSessionAudit(safeSession, safeSessionAction, true,  loggedInUser, tenderMovementId)
    }

   Integer tenderMovementUpdate(int tillId, int safeId, TenderMovementType tenderMovementType, TenderType tenderType, BigDecimal adjustAmount, ReasonCode reasonCode){
        uk.co.wonderlane.wlpos.reporting.Location tillLocation = locationService.getTillLocation(tillId) as uk.co.wonderlane.wlpos.reporting.Location
        uk.co.wonderlane.wlpos.reporting.Location safeLocation = locationService.getOrCreateLocationForSafe(safeId) as uk.co.wonderlane.wlpos.reporting.Location
        return createNewTenderMovement(tillLocation, safeLocation, tenderMovementType, tenderType, adjustAmount, reasonCode)
    }

    Integer tenderMovementUpdate(int safeId, TenderMovementType tenderMovementType, TenderType tenderType, BigDecimal adjustAmount, ReasonCode reasonCode){
        uk.co.wonderlane.wlpos.reporting.Location safeLocation = locationService.getOrCreateLocationForSafe(safeId) as uk.co.wonderlane.wlpos.reporting.Location
        return createNewTenderMovement(null, safeLocation, tenderMovementType, tenderType, adjustAmount, reasonCode)
    }

    void addSafeSessionAudit(SafeSession safeSession, SafeSessionAction safeSessionAction, boolean isAutoGenerated,  User loggedInUser, Integer tenderMovementId){
        if (safeSession != null) {
            safeManagementService.addAudit(safeSession, safeSessionAction, isAutoGenerated, loggedInUser, tenderMovementId)
        }
    }

    void addShiftAudit(Shift shift, ShiftAction shiftAction, boolean isAutoGenerated,  User loggedInUser, Integer tenderMovementId){
        if (shift != null) {
            shiftService.addAudit(shift, shiftAction, isAutoGenerated, loggedInUser, tenderMovementId)
        }
    }

    boolean isSafeActive(int safeId){
        Safe safe = safeService.getSafeById(safeId)
        return safe != null && safe.active
    }

    boolean isOpenShiftAvailable(int tillId){
        Shift shift = shiftService.getOpenShift(springSecurityService.principal.retailerId, springSecurityService.principal.storeId, tillId)
        return shift != null
    }

    List<TillConfiguration> returnAllActiveOpenTills(){
        List<Shift> shiftList = shiftService.getShifts(null) //Load existing active shifts
        List<TillConfiguration> allTills =  getAllActiveTills()
        List<TillConfiguration> openTills = allTills.findAll { till ->
            shiftList.any { shift ->
                shift?.tillId == till?.tillId &&
                        shift?.shiftStatus == ShiftStatus.OPEN
            }
        }
        return openTills
    }

    // This method can generally use for shift balance update
    private void updateShiftBalance(Shift shift, TenderType tenderType, BigDecimal updateAmount){
        updateShiftTenderTotals(shift, tenderType, updateAmount)
        if (tenderType.equals(TenderType.CASH)){
            updateCashDrawer(shift, updateAmount)
        }
        shiftService.saveShift(shift)
    }

    SafeSession safeSessionUpdate(int safeId, TenderType tenderType, BigDecimal cashAmount) {
        List<TenderTotal> addedTenderAmounts = new ArrayList<>()
        if (cashAmount != null && cashAmount.compareTo(BigDecimal.ZERO) > 0) {
            TenderTotal tenderTotal = new TenderTotal(tenderType)
            tenderTotal.value = cashAmount
            tenderTotal.quantity = 1
            addedTenderAmounts.add(tenderTotal)
        }
        //This method will check if any active safe session available if not create new one
        //Then will update tender totals
        return safeManagementService.createNewSafeSessionWithTenderTotals(springSecurityService.principal.retailerId, springSecurityService.principal.storeId,
                safeId, addedTenderAmounts as List<TenderTotal>, true)
    }

    // Generic method for shift's tender total update
    private void updateShiftTenderTotals(Shift shift, TenderType tenderType, BigDecimal updateAmount){
        if (updateAmount != 0) { //update amount either can be negative or positive
            TenderTotal tenderTotal = shift.getTenderTotals().stream()
                    .filter(tt -> tt.getTenderType() == tenderType).findFirst()
                    .orElseGet(() -> {
                        TenderTotal newTenderTotal = new TenderTotal(tenderType);
                        shift.getTenderTotals().add(newTenderTotal);
                        return newTenderTotal;
                    });

            tenderTotal.setQuantity(tenderTotal.getQuantity() + 1);
            tenderTotal.setValue(tenderTotal.getValue().add(updateAmount));
        }
    }

    // Generic method for shift's cash drawer update
    private void updateCashDrawer(Shift shift, BigDecimal cashAmount){
        if (cashAmount != null){
            BigDecimal currentCash = shift.getCashInDrawer()
            if (currentCash == null) {
                currentCash = BigDecimal.ZERO
            }
            BigDecimal newCashAmount = currentCash.add(cashAmount)
            shift.setCashInDrawer(newCashAmount)
        }
    }

    // Method to create new tender movement
    private Integer createNewTenderMovement(uk.co.wonderlane.wlpos.reporting.Location tillLocation, uk.co.wonderlane.wlpos.reporting.Location safeLocation, TenderMovementType tenderMovementType, TenderType tenderType, BigDecimal updateAmount, ReasonCode reasonCode){
        return reportingService.saveTenderMovement(reportingService.createNewTenderMovement(tenderMovementType,
                tenderType,
                tillLocation as uk.co.wonderlane.wlpos.reporting.Location,
                safeLocation as uk.co.wonderlane.wlpos.reporting.Location,
                updateAmount, reasonCode == null ? null : reasonCode.description
                ))
    }

    private User loadLoggedInUser(){
        int id = springSecurityService.principal.id
        User loggedInUser = userService.getUser(id)
        return loggedInUser
    }

}
